### ISSUE TITLE
为什么有的rss订阅源获取失败呢？

### ISSUE THREAD

**Issue by qingsongya** [yang991178/fluent-reader#101]
1、例如这个https://www.hostloc.com/forum.php?mod=rss
2、希望即使是订阅源有问题，也可以支持导入，只不过在订阅列表中用明显的红色表示出该订阅源有问题，我觉得这样更好一些。3、为什么导入后的订阅源排序，不能按照opml文件中的排序来导入呢，导入后排序有点乱了。
4、请支持订阅源地址修改吧！
![RSS报错](https://user-images.githubusercontent.com/53110520/93072397-e7fe4100-f6b3-11ea-88e3-ec277baec92c.png)

**Comment by wanderseeme** [comment]
同问，我的人民网订单也会失效！
