### ISSUE TITLE
代理模式能否支持Clash，例如直接配置127.0.0.1:7890

### ISSUE THREAD

**Issue by cat-sir** [yang991178/fluent-reader#104]
感谢你的程序，非常好用，希望我的这个需求能被开发者看到

**Comment by yang991178** [comment]
见#3，在PAC文件中返回如"HTTP 127.0.0.1:7890"即可。

**Comment by cat-sir** [comment]
> 见[＃3](https://github.com/yang991178/fluent-reader/issues/3)，在PAC文件中返回如“ HTTP 127.0.0.1:7890”即可。

好的，谢谢！

**Comment by cat-sir** [comment]
大佬，还是不太行，这方面的小白，查了一下，下载了个PAC文件，但是后面就不知道怎么弄了。方便指导一下吗

**Comment by jingouwangzi** [comment]
请问正确的URL格式是什么样的

**Comment by jingouwangzi** [comment]
搞定，还好自己有个小服务器

**Comment by zhaoliang0302** [comment]
> 搞定，还好自己有个小服务器

请问怎么解决的，不知道这软件里怎么配置代理

**Comment by leo-56** [comment]
@zhaoliang0302 不知道你解决了没有，这个直接写个 pac 文件，然后挂到 github 上就可以了，手头上暂时没有服务器也没关系，参考我的方式：https://raw.githubusercontent.com/leo-56/files/main/proxy.pac

**Comment by 2-3-5-7** [comment]
家里路由器刷成 openwrt，然后放到 /www  目录下也可以，ip 填路由器的

**Comment by vagrant-psyche** [comment]
windows下可以用这个简单的方法设置代理:

找到安装路径下的Fluent Reader.exe文件，创建桌面快捷方式
修改快捷方式中的目标选项接入代理，添加后缀 --proxy-server=socks5://127.0.0.1:7890
注意引号后面需要加一个空格
我用的是clash，http和socks的代理端口都是7890
![Snipaste_2023-10-22_10-56-24](https://github.com/yang991178/fluent-reader/assets/37809377/75e2e654-699f-4949-a8c4-e1f25110f588)
