### ISSUE TITLE
3 column view

### ISSUE THREAD

**Issue by jamiehoss** [yang991178/fluent-reader#106]
I've got the app installed on a few machines and two of them have three column view but one only has two columns and I can't figure out how to get the same set up on that machine (so I can only see the source list by clicking on the upper left corner). Is there a setting toggle I'm missing?

![twocolumn](https://user-images.githubusercontent.com/19316057/94749701-72040600-0352-11eb-96ef-a4eab44179f3.jpg)

**Comment by yang991178** [comment]
The menu can only be pinned if the window is wide enough.

**Comment by jamiehoss** [comment]
ahhh gotcha, thanks, I redid the resolution and it's pinned now. perfect
