### ISSUE TITLE
Be able to hide built in window controls and use native window border

### ISSUE THREAD

**Issue by Waces** [yang991178/fluent-reader#107]
I use a window manager that doesn't necessitates of the window controls in the program as it is
keyboard oriented, so the built in minimize, maximize and close buttons are both kinda useless in this environment and clash with the window style.

Having an option in the settings to hide the built in window controls and use the system's window border would solve that
and have it look more inline with other programs independently of the system.

![Screenshot_201002_160302](https://user-images.githubusercontent.com/31547648/94960368-26c03380-04c9-11eb-92b6-20bbce218ff7.png)
The window control buttons clashing with the system's visual

![Screenshot_201002_160321](https://user-images.githubusercontent.com/31547648/94960376-2b84e780-04c9-11eb-96a1-85a6d19a760e.png)
Even though the maximize button is pressed, the window isn't maximized because of how the window manager works

**Comment by thebayram** [comment]
Are there any plans for this? Even though I am not using a standalone window manager, the Windows 10 style title bar doesn't really go well with the title bar of other applications I am using.
![image](https://user-images.githubusercontent.com/48856944/110362217-10a73800-8052-11eb-937c-3a05258660fa.png)

**Comment by ralphocdol** [comment]
![Screenshot_20210619_160227](https://user-images.githubusercontent.com/31056871/122635658-c57ed580-d0d4-11eb-835f-909c16594194.png)

I'm also using a different style on my window with KDE. Not having an option to use the Native Window makes it out of place, I do hope you consider adding it.
