### ISSUE TITLE
How topublish windows store ？

### ISSUE THREAD

**Issue by tym3515** [yang991178/fluent-reader#114]
electron-builder create-self-signed-cert --publisher fluent-reader 

 When asked to enter a password ("Create Private Key Password"), please select "None".  

can not create pfx？

**Comment by yang991178** [comment]
You don't need to generate a certificate to publish to windows store, as Microsoft will sign the appx package for you. Certificates are only needed for local testing. You should consult electron-builder for building and signing apps.

**Comment by tym3515** [comment]
thank you
