### ISSUE TITLE
希望左侧的feeds列表能够抽拉，而不是悬浮在文章列表上，遮挡文章列表

### ISSUE THREAD

**Issue by hengsijian** [yang991178/fluent-reader#115]
首先，非常感谢作者。这是我见过的，开源RSS里边最美观、易用的RSS Reader，和iOS的Reeder体验接近。
但是，左侧的feeds列表悬浮在文章列表上，遮挡文章列表，如果能像Reeder一样，做成推拉式的就完美了。

当前版本仅为Beta 0.8，就已经很完善了。并且迭代非常快，非常看好。希望作者加油，另外，对于功能要保持克制，不要随便加一些花哨的功能。祝越来越好

**Comment by yang991178** [comment]
如果窗口够宽，菜单是可以固定显示不遮挡文章列表的
