### ISSUE TITLE
“将↓以下设为已读”，该操作不能同步到freshRSS

### ISSUE THREAD

**Issue by saishangfeixue** [yang991178/fluent-reader#116]
开发作者你好：
      首先感谢你开发的软件。
      我是用freshRSS的fever接口登录的Fluent Reader软件。今天使用中遇到一个问题，描述如下：
1.打开文章列表，在其中一篇文章标题点右键，出现菜单。
2.在“标为已读”选项右侧有个子选项的箭头，点开。
3.选择“将↓以下设为已读”。此步完成后，未读文章内就没有了这批被批量设为已读的文章。
4.点击软件上方的刷新按钮。软件和freshRSS同步，于是这批被标注为已读的文章再次出现在未读列表内。
      这说明“将↓以下设为已读”这个操作，无法同步到freshRSS。（其它操作都是可以同步过去的，包括在主菜单的源上点右键“全部设为已读”，这个操作都是可以同步到freshRSS的。）
      希望做着能拔冗解决下此问题。衷心感谢。
      Best Wishs  :)
                                                                                                                               saishangfeixue
                                                                                                                               2020.10.16

**Comment by yang991178** [comment]
我记得我之前测试过这个问题，原因应该是FreshRSS的Fever API把`before=`参数理解为文章被抓取的时间而不是文章发布时间，建议你去向FreshRSS团队反馈。
