### ISSUE TITLE
Feature request: 提供portable版单文件

### ISSUE THREAD

**Issue by ivysrono** [yang991178/fluent-reader#12]
https://www.electron.build/configuration/nsis.html#portable
取代现在的 win-unpackaged

**Comment by ivysrono** [comment]
虽然我自己打包也没问题，但我想问问为什么不愿意提供？

**Comment by yang991178** [comment]
> 虽然我自己打包也没问题，但我想问问为什么不愿意提供？

Portable启动慢，而且会给人一种绿色版的错觉，实际会写入数据到AppData，不像安装版和store版在卸载时会清理数据。同理没有特殊需求也不建议用unpacked版。
