### ISSUE TITLE
文章順序不對？

### ISSUE THREAD

**Issue by jerryc127** [yang991178/fluent-reader#123]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10 2004]
 - Version [e.g. 0.6.1]

**Additional context**

文章的時間獲取有誤麽？
每次刷新，都是一組組排序的，然後每組都是顯示同一個時間
![image](https://user-images.githubusercontent.com/16351105/97796415-a833ee80-1c4c-11eb-900e-f3e53fbfd98b.png)

我用的是用inoreader導出的
然後我去inoreader查看，發現文章發表的時間是不一樣的
![image](https://user-images.githubusercontent.com/16351105/97796477-7ec79280-1c4d-11eb-894b-0d5d75bcbd59.png)
![image](https://user-images.githubusercontent.com/16351105/97796479-838c4680-1c4d-11eb-9035-e6aa935f70dd.png)
甚至刷新了好幾次，依舊沒有顯示新的文章

**Comment by 9Panda3** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Platform (please complete the following information):**
> 
> * OS: [e.g. Windows 10 2004]
> * Version [e.g. 0.6.1]
> 
> **Additional context**
> Add any other context about the problem here.
> 
> 文章的時間獲取有誤麽？
> 每次刷新，都是一組組排序的，然後每組都是顯示同一個時間
> ![image](https://user-images.githubusercontent.com/16351105/97796415-a833ee80-1c4c-11eb-900e-f3e53fbfd98b.png)
> 
> 我用的是用inoreader導出的
> 然後我去inoreader查看，發現文章發表的時間是不一樣的
> ![image](https://user-images.githubusercontent.com/16351105/97796477-7ec79280-1c4d-11eb-894b-0d5d75bcbd59.png)
> ![image](https://user-images.githubusercontent.com/16351105/97796479-838c4680-1c4d-11eb-9035-e6aa935f70dd.png)
> 甚至刷新了好幾次，依舊沒有顯示新的文章

同样的情况

**Comment by 9Panda3** [comment]
同样的情况
