### ISSUE TITLE
能不能修改文章阅读的字体？用自带的微软雅黑实在是难受

### ISSUE THREAD

**Issue by pureTrue** [yang991178/fluent-reader#124]
如题

**Comment by yang991178** [comment]
默认的字体其实是思源黑体，可以考虑安装这款字体

**Comment by SamToki** [comment]
> 
> 
> 默认的字体其实是思源黑体，可以考虑安装这款字体

希望可以自定义字体，阅读长篇文章还是宋体（明朝体）舒服一些。鄙人是新用户，有幸发现这个颜值爆表的RSS客户端，用一段时间后会考虑捐赠

**Comment by yang991178** [comment]
#109
