### ISSUE TITLE
Add option to open developer tools

### ISSUE THREAD

**Issue by atbest** [yang991178/fluent-reader#136]
Sometimes, some feeds cannot be loaded correctly and it would help a lot to troubleshoot with the developer tools. This can be done by adding a menu entry below "Show hidden articles" in the "View" menu. Thanks.

**Comment by yang991178** [comment]
Developer tools would definitely not be allowed on app stores and complicates the user experience. If you want to debug the feeds, you can always export your data and load them in development mode following build instructions in README.MD, where developer tools are opened by default.
