### ISSUE TITLE
fever服务的一点问题报告

### ISSUE THREAD

**Issue by qingsongya** [yang991178/fluent-reader#148]
我所使用的自建FreshRSS，然后用fluent-reader在本地使用fever同步查看阅读。使用中遇到一个问题，我在FreshRSS中修改了分类，比如把一个订阅源，从分类A移动到了分类B，但是fluent-reader并没有重新同步分类，希望可以支持分类变动的同步。

**Comment by yang991178** [comment]
分组不会自动同步，可以在设置>分组里手动同步

**Comment by qingsongya** [comment]
> 分组不会自动同步，可以在设置>分组里手动同步

如何操作？没看到手动同步的选项啊
![image](https://user-images.githubusercontent.com/53110520/103164649-fcbcaa00-4848-11eb-865b-27cfbe37c6e1.png)
