### ISSUE TITLE
關於更新訂閲源問題

### ISSUE THREAD

**Issue by jerryc127** [yang991178/fluent-reader#155]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

每次點開設置 都顯示 正在更新訂閲源 請稍後
能否增加一個按鈕，讓人點擊去更新訂閲源
而不是一進入設置 就更新訂閲源
因爲更新訂閲源的速度真的很慢，要等很久才更新完，而我只想去設置一下東西

**Comment by yang991178** [comment]
显示更新订阅源只是因为打开设置前正在刷新（比如说因为刚打开应用）。
