### ISSUE TITLE
[request] possibility to redirect the web pages loaded from the feed

### ISSUE THREAD

**Issue by firinael** [yang991178/fluent-reader#157]
**Is your feature request related to a problem? Please describe.**
I'm a grad student with no money looking for an RSS client that will keep me up to date with papers published. One thing that makes my life a little bit more inconvenient is having to open a paper's link externally on a web browser, and then redirecting the page to Sci-Hub.

**Describe the solution you'd like**
I'd like an option to automatically redirect the web page loaded in-app to its equivalent Sci-Hub page, so that I'd be able to read papers in the app. Maybe an implementation of this could also be used for getting through paid news sites' blockers?

(also maybe add an ad-blocking feature as well?)

**Comment by yang991178** [comment]
You should either modify the URL in the source or open in browser and use a browser extension to redirect automatically. I don't think this feature would have enough use cases to justify adding it to the app.
