### ISSUE TITLE
Keyboard shortcuts only works with capitalized letters

### ISSUE THREAD

**Issue by PorridgePi** [yang991178/fluent-reader#159]
**Describe the bug**
The keyboard shortcuts only accept CAPITALIZED letters as hotkeys. When uncapitalized, the shortcuts do not work.

**To Reproduce**
1. Follow the [instructions](https://github.com/yang991178/fluent-reader/wiki/Support#keyboard-shortcuts) about keyboard shortcuts.
2. Press a key without Caps Lock on. (e.g. `m` to mark as read/unread)
3. Nothing happens.

**Expected behavior**
The function of the shortcut key. (e.g. Mark as read/unread for `m`)

**Platform (please complete the following information):**
 - OS: Windows 10 2004
 - Version 0.9.1

**Comment by yang991178** [comment]
Both upper- and lower-case letters are supported. Please check if your input method is blocking the shortcut.

**Comment by PorridgePi** [comment]
Apogies, that did seem to be the problem. Thanks!
