### ISSUE TITLE
Duplicating news from some sources

### ISSUE THREAD

**Issue by thevllad** [yang991178/fluent-reader#162]
**Describe the bug**

If you update the news feed, or restart the program (which as a result updates the feed), news that have already been downloaded are downloaded again. But this only happens to some sources (https://ukr.media/rss/)

**Screenshots**

I started the program for the first time (First downloaded):

![image](https://user-images.githubusercontent.com/58750054/104228055-fb979980-5452-11eb-810b-5865a5fde3d1.png)

I updated the feed twice:

![image](https://user-images.githubusercontent.com/58750054/104228366-6b0d8900-5453-11eb-8f17-b36114d5dd93.png)

**Platform**
 - OS: Windows 10 Pro 1909
 - Version 0.9.1

p.s. My idea is how to solve this problem: to make it possible to configure the update button so that it deletes all articles (as can be done now in the settings, but this is not convenient)

**Comment by yang991178** [comment]
It seems that the pubDate element for this particular feed changes on each refresh. Please contact the provider of the feed to fix it instead.
