### ISSUE TITLE
Certain XML Feeds can't be parsed

### ISSUE THREAD

**Issue by rmccullagh99** [yang991178/fluent-reader#166]
**Describe the bug**
Specific XML feeds aren't being parsed correctly but others are.
I've got a number of RSS/ATOM/XML feeds that work with Fluent Reader, but the below three don't:

**Screenshots**
![image](https://user-images.githubusercontent.com/42370113/104570343-e8303c80-56a5-11eb-8f1d-27df4db92031.png)

**Platform (please complete the following information):**
 - OS: Windows 10 x64
 - Version: 0.9.1

Are these feeds able to be read, or is this something that can be improved in the future?

**Comment by yang991178** [comment]
Related to #170. Will fix in the next release.
