### ISSUE TITLE
Application says that feed is invalid, while W3C says the inverse

### ISSUE THREAD

**Issue by metal3d** [yang991178/fluent-reader#170]
**Describe the bug**
Opening my rss feed: https://www.metal3d.org/index.xml

![image](https://user-images.githubusercontent.com/100080/105859636-0e7ea200-5fed-11eb-90c4-e7f16f8211f6.png)

But W3C says that it's ok:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.metal3d.org%2Findex.xml
![image](https://user-images.githubusercontent.com/100080/105859780-31a95180-5fed-11eb-943a-169af9dccb23.png)

**To Reproduce**
1.Add my feed
2. see error

**Expected behavior**
The feed should be displayed

**Platform (please complete the following information):**
 - OS: [e.g. Fedora 33]
 - Version [e.g. 0.9.0]

**Comment by yang991178** [comment]
It seems that the regular expression parsing XML encoding lacks a greedy modifier. Will fix in the next release.

```js
XML_ENCODING_RE = /^<\?xml.+encoding="(.+)".*?\?>/i // problematic
XML_ENCODING_RE = /^<\?xml.+encoding="(.+?)".*?\?>/i // correct
```
