### ISSUE TITLE
inoreader的文件夹调整和fluent同步问题

### ISSUE THREAD

**Issue by lianfengyeo** [yang991178/fluent-reader#171]
请问下目前遇到inoreader在fluent里设置好后，在官网的网页里调整了文件夹的名字，并进行了删除增加的操作，但是fluent中并没有和官网进行更新，希望作者可以帮忙解决一下可以吗 多谢多谢。

**Comment by yang991178** [comment]
请在“设置”>“分组“>”导入分组“里手动更新
