### ISSUE TITLE
Customizable Hotkey Shortcuts

### ISSUE THREAD

**Issue by barrtailor** [yang991178/fluent-reader#173]
**Is your feature request related to a problem? Please describe.**
Currently, the keyboard shortcuts seem to be hard coded

**Describe the solution you'd like**
The ability to customize which keyboard shortcuts perform each individual certain action

**Describe alternatives you've considered**
Just dealing with it

**Additional context**
N/A

**Comment by yang991178** [comment]
This would add unnecessary complexity to the program. Consider using a key mapper program if you really need this functionality.
