### ISSUE TITLE
一点使用上的小建议

### ISSUE THREAD

**Issue by longshensanjie** [yang991178/fluent-reader#174]
问题描述:
当我的筛选设置成未读, 当我打开一篇新的未读的 Rss 文章时候, 第一时间我没有读完它, 但是只要关掉这篇文章, 它就被设置成已读状态, 一旦我关闭软件, 下次想进来继续读完这篇文章的话我只能重新打开筛选条件设置成全部文章里面去找, 流程很繁琐, 文章量级大的话会特别麻烦

我的需求:
我的日常使用习惯是将文章筛选设置成未读, 方便我去阅读新更新的文章, 针对一篇我阅读了但是实际却未阅读完的文章, 在当前提供的筛选条件下我会倾向于还是将这种文章设置成未读状态,方便我关闭软件后下去进来继续阅读完这篇文章而不是重复我上面问题描述里的流程

需求解决建议:
1.可以在文章最下面设置一个已读的按钮让读者来确定这篇文章真的已经读完, 或者默认未读完 (也可以默认读完, 读者自动设置未读状态, 总之是这种思路)这可能是暂时解决这个问题最简单的方式
2.当然也可以设置已读但未读完的状态, 然后在筛选里面增加选项使其能显示未读和未读完的选项也是一种解决方式, 这种方式可能会涉及到之前的东西会有比较大的改动

**Comment by yang991178** [comment]
在文章界面点击星标左边的圆圈可以标为未读

**Comment by longshensanjie** [comment]
好的, 感谢你的回复, 之前未留意到这个小圆圈
