### ISSUE TITLE
Flathub version has not been updated

### ISSUE THREAD

**Issue by chrbayer** [yang991178/fluent-reader#176]
**Describe the bug**
The version on flathub is still 0.90.

**To Reproduce**
1. Check version on flathub

**Expected behavior**
Current version available at flathub

**Comment by yang991178** [comment]
I am not involved in the flathub version. Maybe you should contact the maintainer instead.

**Comment by chrbayer** [comment]
Thanks, I was not aware that this is a different person. I informed him and noe it has been update, so close the issue.
