### ISSUE TITLE
Fluent Reader 订阅源抓取的内容重复

### ISSUE THREAD

**Issue by PyGroot** [yang991178/fluent-reader#178]
[每次刷新，都会抓取三篇文章，但是抓取的内容如果上次刷新已经存在，这次刷新仍会再抓取一次，导致内容重复。

订阅源是自己搭建的RSSHUB

**Comment by yang991178** [comment]
如果每次抓取的文章时间不同则会判断成不同的文章，请检查rsshub能否输出正确时间

**Comment by wuhanhui** [comment]
我也有这个问题，抓取出来的xml某条内容只有一条数据，但是隔断时间会出现两条记录。

![image](https://user-images.githubusercontent.com/9048191/108697037-4968ec80-753d-11eb-8452-45022f0828e4.png)
xml文件 ,后缀改了一下
[10119428.txt](https://github.com/yang991178/fluent-reader/files/6021358/10119428.txt)

**Comment by PyGroot** [comment]
> 我也有这个问题，抓取出来的xml某条内容只有一条数据，但是隔断时间会出现两条记录。
> 
> ![image](https://user-images.githubusercontent.com/9048191/108697037-4968ec80-753d-11eb-8452-45022f0828e4.png)
> xml文件 ,后缀改了一下
> [10119428.txt](https://github.com/yang991178/fluent-reader/files/6021358/10119428.txt)

其实是错觉，你把刷新时间改一下，然后你手动刷新试试看，每次刷新都会获取一次推送，导致有重复的订阅内容

**Comment by PyGroot** [comment]
> 如果每次抓取的文章时间不同则会判断成不同的文章，请检查rsshub能否输出正确时间

别关闭问题啊，我手机上用的reader就没有这个重复的问题
