### ISSUE TITLE
将筛选设置为“仅未读文章”时，看完一篇文章，它仍然出现在界面上，能否把它移除？

### ISSUE THREAD

**Issue by WellFolg** [yang991178/fluent-reader#179]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10 2004]
 - Version [e.g. 0.6.1]

**Additional context**

**Comment by yang991178** [comment]
文章在刷新后就会被移除。
