### ISSUE TITLE
希望增添广告拦截或自定义拦截

### ISSUE THREAD

**Issue by XieL1989** [yang991178/fluent-reader#18]
希望能够浏览页面能够想浏览器一样结合Adguard的广告拦截及过滤规则拦截，这样浏览界面会更加舒爽。强烈支持！！

**Comment by yang991178** [comment]
目前没有加强内置webview的计划，但是你可以通过偏好设置下的PAC代理设置屏蔽广告脚本，可以参考https://github.com/essandess/easylist-pac-privoxy 。

**Comment by ixinshang** [comment]
臣复议。
