### ISSUE TITLE
【bug】WIN10 19042.804 UWP版不加载了

### ISSUE THREAD

**Issue by err44** [yang991178/fluent-reader#184]
![Snipaste_2021-02-10_19-59-54](https://user-images.githubusercontent.com/59483300/107507614-ca89c080-6bda-11eb-8770-650bffed19c7.jpg)
![Snipaste_2021-02-10_20-02-40](https://user-images.githubusercontent.com/59483300/107507719-f147f700-6bda-11eb-833c-848ab74bf94e.jpg)

**Comment by yang991178** [comment]
开始菜单右键>更多>应用设置>修复或重置试试。

**Comment by err44** [comment]
> 开始菜单快捷键>更多>应用设置>修复或重置试试。

试过后还是无加载。我是更新系统补丁重启后变成这样的。

**Comment by yang991178** [comment]
无法复现，请重装应用再看看

**Comment by err44** [comment]
> 无法复现，请重装应用再看看

请问数据如何备份。可以导入到exe版吗？

**Comment by yang991178** [comment]
> 请问数据如何备份。可以导入到exe版吗？

UWP数据在`AppData\Local\Packages\25286HaoyuanLiu.FluentReader_xxx\LocalCache\Roaming\fluent-reader`
EXE数据在`AppData\Roaming\fluent-reader`

估计是数据哪里损坏了，建议直接清除数据

**Comment by err44** [comment]
几十条订阅数据全没了。。。真的没办法提取了？他只是软件BUG读不出来吧？

**Comment by err44** [comment]
那如何回退版本？有可能是更新后才bug了。老版本或许能读取数据

**Comment by err44** [comment]
算了。我重置吧
