### ISSUE TITLE
Option to open externally by default on item click

### ISSUE THREAD

**Issue by lmorchard** [yang991178/fluent-reader#185]
When I read feeds, I like to skim through fast and open up what looks interesting in browser tabs. I don't like to read within the feed reader app itself.

Currently, I can do this by right clicking and picking "Open Externally". But, this is cumbersome and requires a right click then a menu click every time.

I'd really it if I could just change the left-click default to open externally rather than read within the app.

**Comment by yang991178** [comment]
You can set the open target to open externally on a per-source basis in settings.

**Comment by lmorchard** [comment]
Per-source meaning a setting change for every feed? I have 400 or so feed subscriptions, I'd like to set this.globally for all at once

**Comment by yang991178** [comment]
I don't think it is likely that I'll work on that any time soon. Alternatively, use the middle button or hold CTRL when clicking on the item.
