### ISSUE TITLE
【bug】部分订阅源导入失败

### ISSUE THREAD

**Issue by absir1949** [yang991178/fluent-reader#19]
举例：https://github.com/tenpiece/wxrss

这种订阅源，无法导入，提示导入失败

**Comment by yang991178** [comment]
版本0.3.3测试了一些都可以导入，具体是哪个链接？

**Comment by absir1949** [comment]
举例：
[开智学堂](https://qnmlgb.tech/v1/publicrss?i=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JfaWQiOiI1YjllOGQwYTI0NGQ0ZTc4Nzc0YTAwNzciLCJ2ZXJzaW9uIjoidjEifQ.F3MDZZRCLiQ4Lu79XOReX0cYBv1NDEyTcd7OgsKy_fs)

**Comment by yang991178** [comment]
请查找一下列表看看有没有重复添加

**Comment by absir1949** [comment]
好，谢谢!的确已经添加过了，谢谢!
