### ISSUE TITLE
A method to import and export config

### ISSUE THREAD

**Issue by cdobbyn** [yang991178/fluent-reader#191]
**Is your feature request related to a problem? Please describe.**
It's kind of frustrating that it's not possible to simply import or export fluent-reader config. Instead the only option is to sync with another platform (which doesn't really solve the issue either). My particular use case is I setup my workstation using Ansible so that when I need to move between my desktop or laptop I have everything I need.

**Describe the solution you'd like**
The most ideal situation would be the ability to either put a config file somewhere and have fluent-reader consume that on startup.

Alternatively a CLI or script that does this.

Less effective but also relatively acceptable is a simple import/export function from within the app.

**Describe alternatives you've considered**
To my knowledge there's no way to do this.

**Additional context**
Most RSS readers are shit, this one's quite good. I'm hoping you'll consider this feature. It'd be nice to maintain a list of RSS feeds and be able to back that config up somewhere. I don't care about storing messages, just the application config.

**Comment by yang991178** [comment]
You can export and import all data in preferences under settings.

**Comment by cdobbyn** [comment]
Oh I'm completely blind, thanks @yang991178. Sorry for wasting your time.
