### ISSUE TITLE
Feature request: Load full content or website automatically

### ISSUE THREAD

**Issue by tiritto** [yang991178/fluent-reader#192]
Having an option to load full content (or even load the entire website) of the article is amazing, but having to click on the load button each time we switch between articles feels very unproductive in a long run. I would like to recommend a new feature that would allow the user to automatically load the full content of the article or load the entire website (depending on user choice) right away when the article is opened, rather than waiting for an additional prompt.

Such a feature could have its own place in the settings which would allow the user to choose one of three options:

**Default reading mode:**
- Show summary _(default option)_
- Load full content
- Load website

In the future such a feature could also be extended to be applied on per group or per source basis, allowing users to decide for themselves what exactly should be auto-loaded and in which way.

**Comment by yang991178** [comment]
You can opt to load full content or website by default on a per-source basis in settings. Just select a source and choose an open target option.
