### ISSUE TITLE
功能需求：订阅源URL修改

### ISSUE THREAD

**Issue by qingsongya** [yang991178/fluent-reader#193]
可以支持订阅源URL修改吗？
因为不支持修改订阅源URL，会遇到这样的问题，订阅源的地址发生了变化，比如是RSSHUB生成的，或者其它类似的原因，如果RSSHUB挂了，需要重新修改订阅源的域名URL。虽然可以使用，删除这个订阅源，再重新订阅的办法，但是重新订阅以后，如果有排序的需求，还要重新为订阅源进行排序，手动命名过的订阅源，也同样需要重命名。只有一个订阅源需要操作的话还简单些，再多些就更麻烦了，所以请求添加订阅源URL修改的功能。

**Comment by wuhanhui** [comment]
非常支持，目前只能删掉，然后自己在添加修改后的

**Comment by yang991178** [comment]
如果有这种需求导出opml替换所有rsshub地址再导入即可。除rsshub外正常情况下订阅源地址不会改变，修改订阅源地址可能导致两个不同订阅源混在一起。
