### ISSUE TITLE
抓取出来的xml内容只有一条数据，但是隔断时间会出现重复记录。

### ISSUE THREAD

**Issue by wuhanhui** [yang991178/fluent-reader#194]
我也有这个问题，抓取出来的xml某条内容只有一条数据，但是隔断时间会出现两条记录。

![image](https://user-images.githubusercontent.com/9048191/108697037-4968ec80-753d-11eb-8452-45022f0828e4.png)
xml文件 ,后缀改了一下
[10119428.txt](https://github.com/yang991178/fluent-reader/files/6021358/10119428.txt)

_Originally posted by @wuhanhui in https://github.com/yang991178/fluent-reader/issues/178#issuecomment-783280834_

**Comment by yang991178** [comment]
rsshub输出的标题不一样就会出现多条记录，这是正常现象
