### ISSUE TITLE
Feature request: Option to always load articles as webpages for groups

### ISSUE THREAD

**Issue by VivaHow** [yang991178/fluent-reader#195]
**Is your feature request related to a problem? Please describe.**
Some websites don't display full content of the article and also some RTL websites look weird when they're in the normal mode.

**Describe the solution you'd like**
An option in the settings to always load the articles as a webpage in the built-in browser for the entire group.
I know it's possible for a specific source (Answered in issue #192), but it's not possible for the entire group.

**Describe alternatives you've considered**
An option in the settings to always load the articles as a webpage for specific groups.

**Additional context**
A lot of websites only displays a snippet of the article's content and I always find myself clicking the icon "Load webpage".

**Comment by yang991178** [comment]
You can set it for each source in the group. I don't think I'll ever work on this as mentioned in #185.
