### ISSUE TITLE
请问能支持本地代理吗

### ISSUE THREAD

**Issue by jingouwangzi** [yang991178/fluent-reader#196]
现在只支持pac代理，请问能支持clash for windows，直接127.0.0.1:7890这种代理吗？

**Comment by yang991178** [comment]
#104

**Comment by vagrant-psyche** [comment]
windows下可以用这个简单的方法设置代理:

找到安装路径下的Fluent Reader.exe文件，创建桌面快捷方式
修改快捷方式中的目标选项接入代理，添加后缀 --proxy-server=socks5://127.0.0.1:7890
注意引号后面需要加一个空格
我用的是clash，http和socks的代理端口都是7890
![Snipaste_2023-10-22_10-56-24](https://github.com/yang991178/fluent-reader/assets/37809377/0e4bcb37-9438-4fbf-91b6-cc14e1b5d617)

**Comment by Syed-Wang** [comment]
在 clash 里点击 **解除UWP网络限制**，然后找到 fluent reader 勾选上保存即可，fluent reader 软件内也不用设置代理了。

和使用代理就不能使用微软商店一个道理，因为默认不与本地网络连通，需要针对应用开启 loopback 豁免。

**Comment by woq** [comment]
> windows下可以用这个简单的方法设置代理:
> 
> 找到安装路径下的Fluent Reader.exe文件，创建桌面快捷方式 修改快捷方式中的目标选项接入代理，添加后缀 --proxy-server=socks5://127.0.0.1:7890 注意引号后面需要加一个空格 我用的是clash，http和socks的代理端口都是7890 ![Snipaste_2023-10-22_10-56-24](https://github.com/yang991178/fluent-reader/assets/37809377/0e4bcb37-9438-4fbf-91b6-cc14e1b5d617)

最新Release在应用偏好内启用代理http/https无效果 socks5提示url不符合规范 使用此方法成功解决
