### ISSUE TITLE
Application doesn't respect windows titlebars decoration in Linux

### ISSUE THREAD

**Issue by KonstantMan** [yang991178/fluent-reader#197]
**Describe the bug**

**To Reproduce**
1. Just open the application in linux 
**Expected behavior**
Change the windows titlebars decoration based on the theme 

**Platform (please complete the following information):**
 - OS: [e.g. Arch Linux ]
 - Version 1.0.0

**Comment by yang991178** [comment]
This is the intended behavior as there's no way to apply system theme to a frameless window. I don't think adding an option to show the (double) frame would be worth it.
