### ISSUE TITLE
Add vim keybindings

### ISSUE THREAD

**Issue by Albonycal** [yang991178/fluent-reader#199]
#### Add an option to enable vim keybindings 
This will make navigating easy with the keyboard

**Comment by yang991178** [comment]
This is not a text editor and I don't think vim shortcuts will make sense here. There're only a few shortcuts to memorize and you can use standard navigation for most cases (arrow keys, pg up/down, enter, esc, etc.).

**Comment by Albonycal** [comment]
Maybe just add jkhl to navigate? On a laptop keyboard arrow keys are hard to reach...
Thank you for your awesome RSS reader
:) 
@Albonycal

**Comment by nicolasshu** [comment]
@Albonycal, I am going to later fork this repo and then add that to the key bindings. I'll try to do a pull request, but it may end up being in a direction away from which @yang991178 wishes to go, but let's give it a try!

**Comment by Albonycal** [comment]
That would  be great

**Comment by nicolasshu** [comment]
I've added just the j/k to switch between the articles. I.e. 
j = next
k = previous

I wasn't sure how to add that for the navigation itself on the nav.tsx

**Comment by nicolasshu** [comment]
https://github.com/nicolasshu/fluent-reader/commit/fd7072c61bf7aa00f61f2a97692ff36e94834b6d

**Comment by nicolasshu** [comment]
I'll try to do a pull request right now

**Comment by Albonycal** [comment]
I will have to compile it, will try later 👍
