### ISSUE TITLE
Fever API Support

### ISSUE THREAD

**Issue by hoilc** [yang991178/fluent-reader#2]
**Is your feature request related to a problem? Please describe.**
sync with self-hosted RSS service

**Describe the solution you'd like**
support fever API (Tiny Tiny RSS, miniflux, etc.)

**Comment by Alkarex** [comment]
[FreshRSS](https://github.com/FreshRSS/FreshRSS) is adding Fluent-Reader to its documentation https://github.com/FreshRSS/FreshRSS/pull/3140
For the record, FreshRSS also supports the Google Reader API (same as Inoreader), which is more powerful and efficient.
