### ISSUE TITLE
Has the tri-column view been deleted now? 

### ISSUE THREAD

**Issue by Franklittleboy** [yang991178/fluent-reader#201]
现在三栏式视图给删了吗？找了好久一直找不到这个设置呢。感觉这种视图最方便。

Has the tri-column view been deleted now? I haven't been able to find this setting for a long time. I feel that this view is the most convenient.

**Additional context**
![三栏式视图](https://user-images.githubusercontent.com/54013763/109411489-7144ce00-79dd-11eb-857e-1e7a2f4b98a6.png)

**Comment by yang991178** [comment]
请拉宽窗口。

**Comment by Franklittleboy** [comment]
原来是这样，多谢多谢！完美了！
