### ISSUE TITLE
I open the appimage but it doesn't have any interface

### ISSUE THREAD

**Issue by KonstantMan** [yang991178/fluent-reader#209]
**Describe the bug**
Until yesterday the app worked just fine today it opens but i don't see any interface ,i downloaded again and even tried with the appimage launcher 

**To Reproduce**
1. Go to ''Fluent.Reader.1.0.0.AppImage"
2. Click on ''Fluent.Reader.1.0.0.AppImage'
3. See error

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS:  [ Arch Linux : GNOME ]
 - Version [v1.0.0]
![Screenshot from 2021-03-03 16-44-52](https://user-images.githubusercontent.com/56481040/109823480-a3099f00-7c40-11eb-83d4-43dfd359ae1d.png)
]

**Comment by yang991178** [comment]
The data of the application may be corrupted for some reason. You can manually delete the data of the app in fluent-reader folder under `$XDG_CONFIG_HOME` or `~/.config`.
