### ISSUE TITLE
Undo action instead of confirmation dialog for "Mark as all read"

### ISSUE THREAD

**Issue by Ojd2000** [yang991178/fluent-reader#213]
Currently, whenever you wanna "mark as all read" some articles, you are asked for a confirmation. I personally do not like this approach, since it takes time and attention to what I'm doing.

A good alternative would be the more modern approach to provide an "undo" action after having them marked as read. The undo action is not strictly necessary, but it's a good habit to take some precautions :)

Actually, since everyone has his/her own preference, I'd consider the idea of an option for the user to decide which one to have, either the current dialog or the undo approach.

Thanks

**Comment by yang991178** [comment]
The current plan is to remove the pop-up window in the next build and instead show a context menu that includes options to mark articles X days ago as read. Undoing the action would be very hard to implement for sync services that don't support this feature natively.

**Comment by Ojd2000** [comment]
That's a good idea!
Just for the record, you could "fake" the undo action: mark as read only if the undo button was not pressed and only when it has expired.

**Comment by yang991178** [comment]
The new mark as read menu has been added in the latest version, so I'm closing this issue.
