### ISSUE TITLE
Unable to login in Feedbin

### ISSUE THREAD

**Issue by xplosionmind** [yang991178/fluent-reader#215]
**Describe the bug**
I get a connection error message when I try to login to Feedbin. Nevertheless, I am connected to the internet and everything seems to work.

**To Reproduce**
1. Go to `Preferences` > `Service`
2. Attempt to login with the default endpoint
4. Error: *`Cannot connect to service`*: `Please check the service configuration or network status`

**Expected behavior**
I should be able to login

**Screenshots**

**Platform (please complete the following information):**
 - OS: Ubuntu 20.10
 - Version: 1.0.0

**Additional context**
It may be a problem related to my password characters? It includes non-ASCII values, too

**Comment by yang991178** [comment]
Feedbin API uses Base64 encoding and only supports ASCII strings. Please try updating your password and see if it works.
