### ISSUE TITLE
option for removed hover animation while "card view " turn on

### ISSUE THREAD

**Issue by msongz** [yang991178/fluent-reader#220]
**Is your feature request related to a problem? Please describe.**
add an option to stop the animation while mouse hover at card view.
i do not care too much about the detail info of the item in card view other than the thumbnail.

**Describe the solution you'd like**
just stop animation

**Describe alternatives you've considered**
or offset 1 or 2 pixel up

**Comment by yang991178** [comment]
Unfortunately I can't keep adding features to cater to everyone's taste. Since this is an open source app, you [can always change the CSS](https://github.com/yang991178/fluent-reader/blob/7d2860fda163ac04f9b02d31ac159d55ae2a7973/dist/styles/cards.css#L138) and build the package yourself.
