### ISSUE TITLE
(electron) Security Warning received during install

### ISSUE THREAD

**Issue by OSINTNewbie** [yang991178/fluent-reader#221]
I'm new to github, so this may not be the correct location to post this information. If not, my apologies.

I just installed Fluent-Reader onto a Ubuntu 20.04 machine by using the AppImage. Downloaded the file, enabled it to be executable, and then executed app through the terminal. The app opened, but I received the security warning listed below. Was there an error in how I installed the app, or is this a bug. Is the app safe to use with this issue, or should I wait until the issues is resolved? 

Thank you for any help you can provide.

(electron) Security Warning: A WebContents was just created with both webviewTag and contextIsolation enabled.  This combination is fundamentally less secure and effectively bypasses the protections of contextIsolation.  We strongly recommend you move away from webviews to OOPIF or BrowserView in order for your app to be more secure

**Comment by yang991178** [comment]
It seems that webview in electron is already implemented with OOPIF and this message may be outdated. There are sufficient security precautions implemented in this app in my opinion, but again this app (just like every other open source projects) comes with no warranty whatsoever.
