### ISSUE TITLE
Windows10动态磁贴支持

### ISSUE THREAD

**Issue by MrZanHQ** [yang991178/fluent-reader#222]
我很喜欢Fluent Reader这个UWP平台的RSS阅读器，同样我也非常喜欢通过开始菜单的动态磁贴快速预览信息，我注意到Fluent Reader的磁贴可以以“宽"大小显示，因此我希望Fluent Reader可以添加对开始菜单动态磁贴的支持，最好可以让用户选择在动态磁贴上选择显示什么内容（显示已读或者全部、对某订阅单独关闭磁贴预览）

另一个UWP平台的本地RSS阅读器Newsflow也实现了动态磁贴的支持，可以参考下图

![image](https://user-images.githubusercontent.com/73877228/113004566-47322780-91a6-11eb-902f-661b6c2d95bb.png)

**Comment by zhoushengdao** [comment]
这是一个很好的主意，我也希望如此

**Comment by yang991178** [comment]
Windows 11中移除了动态磁贴，所以目前不打算支持。

**Comment by nljxlove** [comment]
Windows 11可以通过https://github.com/zetaloop/ExplorerPatcher修复Win10开始菜单，希望可以支持动态磁贴功能。
