### ISSUE TITLE
Possibility to add email newsletter as a source

### ISSUE THREAD

**Issue by stlsht** [yang991178/fluent-reader#226]
Would be cool. But I don't know that's even possible. 
Inoreader got that option, but even in a paid version you're able to add only one newsletter, so that makes me think it's not so easy. But - cool feature, so I'm requesting. 

Really appreciate your work. Thank you!

**Comment by yang991178** [comment]
I'm afraid this would require building an entire email client into the app, which would be too much work. Please check if the newsletter provider also offers an RSS source or use another online service that converts emails into RSS.
