### ISSUE TITLE
Global setting to enable full content/webpage as default (for both fluent-reader and fluent-reader lite)

### ISSUE THREAD

**Issue by githupper** [yang991178/fluent-reader#229]
Current implementation is set on a per subscription basis. This is very tedious when a user has hundreds of subscriptions and having to set one by one is very time consuming. This is useful if the user prefer to customize different views for each subscription but not users who prefer webpage as default as they wont have missing images unlike full content.

Would like to ask you to consider to add a global function for a default view of either full content/webpage.

Thank you

**Comment by yang991178** [comment]
#224
