### ISSUE TITLE
Add custom "Open with..." context menu option

### ISSUE THREAD

**Issue by catthou** [yang991178/fluent-reader#234]
Sometimes I don't want to open the urls to articles with my default application, but a custom application (like a browser with a specific user profile, or a download script), so I think it would be useful to allow for adding custom commands or applications that I can set as default article handler.

**Comment by yang991178** [comment]
I don't think this is possible with Electron, at least without any third-party native module. The default API only allows the app to open the default app for a given URI type. Please feel free to correct me if there exist workarounds for this.

**Comment by snylonue** [comment]
@yang991178 I'm not a js developer, but I think you can use [`child_process`](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback).
