### ISSUE TITLE
Error：添加订阅源时出现错误

### ISSUE THREAD

**Issue by Root-1404** [yang991178/fluent-reader#236]
在添加reddit和百度出现Error错误提示；然后我将网址切换到irreader软件却没有报错
【我想请问下这种情况该怎么解决】
**Screenshots**

![捕1获](https://user-images.githubusercontent.com/77722478/116020672-5d35e980-a679-11eb-8c19-3a7ae919b54d.PNG)
![捕获](https://user-images.githubusercontent.com/77722478/116020676-5e671680-a679-11eb-8a2c-ae0c7ab8d1c1.PNG)

**Platform (please complete the following information):**
 - OS: Windows 7 1069 x64
 - Version 1.0.0

**Comment by yang991178** [comment]
订阅源地址？

**Comment by Root-1404** [comment]
> 订阅源地址？

https://www.reddit.com/
https://www.baidu.com/
https://www.csdn.net/
我也在尝试在网上找解决方法

**Comment by yang991178** [comment]
网页地址不是订阅源地址，请使用如 https://www.reddit.com/.rss 之类的xml地址。

**Comment by Root-1404** [comment]
> 网页地址不是订阅源地址，请使用如 https://www.reddit.com/.rss 之类的xml地址。

意思说我可以去加后缀.rss然后去订阅吗？rss这个后缀是对任何网站都是通用的吗？

**Comment by yang991178** [comment]
> 意思说我可以去加后缀.rss然后去订阅吗？rss这个后缀是对任何网站都是通用的吗？

不是，不同网站不一样

**Comment by Root-1404** [comment]
> > 意思说我可以去加后缀.rss然后去订阅吗？rss这个后缀是对任何网站都是通用的吗？
> 
> 不是，不同网站不一样
如果我需要将其他网站变成RSS订阅源话，我该怎样去操作实现？例如youtube、pixiv、推特等【能方便告诉我怎么去实现吗】

**Comment by Root-1404** [comment]
> > > 意思说我可以去加后缀.rss然后去订阅吗？rss这个后缀是对任何网站都是通用的吗？
> > 
> > 
> > 不是，不同网站不一样
> > 如果我需要将其他网站变成RSS订阅源话，我该怎样去操作实现？例如youtube、pixiv、推特等【能方便告诉我怎么去实现吗】

还有个问题是，在我成功添加链接后。能像reddit这样无限瀑布流那样下拉加载页面吗

**Comment by 929KC** [comment]
![在这里插入图片描述](https://img-blog.csdnimg.cn/11d8090fbb834b599cc22d298dae2fb6.png)
win11电脑,使用RSSHUb插件导入的订阅源出错

**Comment by oldhelps** [comment]
添加订阅源时出错: Error: 429
