### ISSUE TITLE
希望标题已读后能用字体或者颜色进行区分

### ISSUE THREAD

**Issue by YOU-Y8** [yang991178/fluent-reader#248]
目前阅读器中读过的标题和未读标题外官没有区别，没法区分。希望以后可以用字体粗细或者标签颜色深浅进行区分。

**Comment by yang991178** [comment]
列表视图下可以 右键单击文章>视图>暗化已读文章 来开启，杂志视图下也有类似效果。其它视图因美观原因不打算添加。

**Comment by YOU-Y8** [comment]
用的卡片模式所以一直没发现还有这选项，能考虑卡片模式也用颜色深浅区分一下已读未读吗？现在卡片模式好像只有黄色小圆点能看出是未读的。
另外这个选项能不能挪到设置里，只有在列表模式上点右键才弹出来实在太隐蔽了

**Comment by yang991178** [comment]
试过了，在有色背景下并不好看/明显，所以没有打算增加这个选项。
