### ISSUE TITLE
一个订阅源只能保留10篇文章到本地

### ISSUE THREAD

**Issue by jonyzhao** [yang991178/fluent-reader#252]
**Describe the bug**
如果刷新，之前的文章就看不到了，只展示最新的10篇未读文章。看上去是客户端做了限制？

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10 2004]
 - Version [e.g. 0.6.1]

**Additional context**

**Comment by yang991178** [comment]
并没有限制文章数量，是不是开启了仅未读文章视图？
