### ISSUE TITLE
App no longer works. Is there a file where articles marked as important are saved to?

### ISSUE THREAD

**Issue by elmonteanalogo** [yang991178/fluent-reader#253]
I used the flatpak fluent reader on debian stable for a few months until it stopped working some weeks ago. Will just display an empty grey box now. It would be a lifesaver if there is any way to recover the articles I marked as important.

**Comment by yang991178** [comment]
The data of the application may be corrupted for some reason. You can move the data of the app from `fluent-reader` folder under `$XDG_CONFIG_HOME` or `~/.config` to some other places and see if the app will work. The articles are stored in indexedDB in Chromium data.

**Comment by yang991178** [comment]
Try upgrading to 1.0.2. If no article shows up in this build, I'm afraid that the DB had been corrupted.
