### ISSUE TITLE
点击文章删除源

### ISSUE THREAD

**Issue by zzhzero** [yang991178/fluent-reader#255]
**Is your feature request related to a problem? Please describe.**
有时候我会因为某篇文章想要删除这个文章的源，现有逻辑需要肉眼定位到源，然后删除，这在源特别多的时候非常麻烦。
**Describe the solution you'd like**
右击文章封面的菜单中(或者文章正文菜单中)加入删除源选项
**Additional context**
![image](https://user-images.githubusercontent.com/26578967/120507160-2467fd80-c3f9-11eb-9d00-99310a1b906f.png)
![image](https://user-images.githubusercontent.com/26578967/120507207-2e89fc00-c3f9-11eb-8592-5269efd68df7.png)

**Comment by yang991178** [comment]
菜单空间有限无法加入那么多功能，抱歉
