### ISSUE TITLE
Native/System window support

### ISSUE THREAD

**Issue by ralphocdol** [yang991178/fluent-reader#268]
**Is your feature request related to a problem? Please describe.**
Having a window different from my customization makes it look out of place. I use KDE as my default Desktop Environment, it has a ton of customizability, one of which is the window decorations.

**Describe the solution you'd like**
Just have an option to use the native or system window

**Additional context**
Here's a screenshot for comparison, native vs fluent reader's window: ![Screenshot_20210619_160227](https://user-images.githubusercontent.com/31056871/122635935-1e02a280-d0d6-11eb-8663-4e9bc9273c05.png)

This is also related to a closed unresolved issue #107.

**Comment by yang991178** [comment]
#212
