### ISSUE TITLE
flatpak app not starting

### ISSUE THREAD

**Issue by snooOranges** [yang991178/fluent-reader#272]
**Describe the bug**
app suddenly wouldn't start despite reinstalling or running it explicitly from terminal. working perfectly all this while.

**Platform (please complete the following information):**
 **- OS: POP OS (ubuntu)
 - Version 5.11.0.7614**

**Additional context**
**$ flatpak info me.hyliu.fluentreader**
Fluent Reader - Modern desktop RSS reader
-   ID: me.hyliu.fluentreader
-   Ref: app/me.hyliu.fluentreader/x86_64/stable
-   Arch: x86_64
-   Branch: stable
-   Version: 1.0.2
-   License: BSD-3-Clause-Clear
-   Origin: flathub
-   Collection: org.flathub.Stable
-   Installation: system
-   Installed: 195.8 MB
-   Runtime: org.freedesktop.Platform/x86_64/20.08
-   Sdk: org.freedesktop.Sdk/x86_64/20.08

-   Commit: 7439943e57bfbcd5bdf9aeb712217bb9ca45ec8731cce195d0bcc2406f24c847
-   Parent: 48118cbb56d4e939839c4fff2b6be102c2b2deced4f234234d857587d3e4cad2
-   Subject: Update fluent-reader.git to 1.0.2 (#4) (de55f6e7)
-   Date: 2021-06-28 14:59:53 +0000

**Comment by yang991178** [comment]
Please report flatpak-related issues to https://github.com/flathub/me.hyliu.fluentreader
