### ISSUE TITLE
支持文章和UI的自定义字体

### ISSUE THREAD

**Issue by cesaryuan** [yang991178/fluent-reader#278]
**Describe the solution you'd like**
在Windows上，对于高DPI的屏幕（笔记本）而言，默认字体微软雅黑的渲染极其糟糕，所以希望能够修改默认字体。
为了对比，我在下面放上了`微软雅黑`和`苹方`两种字体的对比

**Additional context**
苹方：
![image](https://user-images.githubusercontent.com/35998162/124850535-60334b80-dfd3-11eb-91f2-94782ce16a10.png)
微软雅黑：
![image](https://user-images.githubusercontent.com/35998162/124850552-66292c80-dfd3-11eb-9514-442f13fb8e25.png)

**Comment by yang991178** [comment]
#109 #124
