### ISSUE TITLE
"Simple" Ad blocking for web viewer

### ISSUE THREAD

**Issue by bakinazik** [yang991178/fluent-reader#281]
**Is your feature request related to a problem? Please describe.**
If the feed links are to be opened with the browser viewer, there should be ad blocker support.

**Describe the solution you'd like**
As I wrote above, adblock support should come.

**Comment by yang991178** [comment]
You can always use PAC scripts for simple AD blocking or use a global blocker for better effects. This is a duplicate of #18 (not in english).

**Comment by xmha97** [comment]
+1
