### ISSUE TITLE
Add an option to have the sources menu as a permanent column

### ISSUE THREAD

**Issue by vosian** [yang991178/fluent-reader#282]
**Is your feature request related to a problem? Please describe.**
Loading all articles at once tends to be overwhelming, there are some sources that I only check depending on my mood, so I tend to show by category, but when changing from a category to another it gets tiresome to have to keep invoking the sources menu.

**Describe the solution you'd like**
Having the option to have it as a column, much like how the article list appears as a "column" when in list view.

**Comment by yang991178** [comment]
You can pin the sources menu when the window is wide enough.

**Comment by Capivaresco** [comment]
I'm sorry for reviving this issue thread, but where in the world is the button for pin the column? I can't find it when the window is maximized, nor when I make the window as wide as I can.
![Captura de tela de 2021-07-27 21-17-19](https://user-images.githubusercontent.com/65175037/127243837-7177c13d-3afc-4ada-bd83-aee26fa238c2.png)

**Comment by thiagovicino** [comment]
I have the same problem and I'm using the magazine view.
