### ISSUE TITLE
After marking all feeds as read, -1 appeared instead of 0 or nothing

### ISSUE THREAD

**Issue by TriptoAfsin** [yang991178/fluent-reader#283]
[**Describe](url) the bug**
After marking all feeds as read, -1 appeared instead of 0

Sorry I don't know how to reproduce this issue, all I can provide is screenshot

**Screenshots**
[Screenshot Link](https://i.imgur.com/BFbXF6e.png)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10 2004]
 - Version [e.g. 0.6.1]

**Comment by mudfly** [comment]
I find this behavior to be odd, and came here to see if this has been reported.

Platform
- OS: Linux Mint 20.2 Cinnamon
- Version: Fluent Reader 1.0.1

**Comment by yang991178** [comment]
Duplicate #216. Seems to be a valid bug, but still trying to reproduce this. It would be helpful if someone is willing to export their app data with the bug and send it to me.

**Comment by mudfly** [comment]
> Duplicate #216. Seems to be a valid bug, but still trying to reproduce this. It would be helpful if someone is willing to export their app data with the bug and send it to me.

Can you explain what you want exported? Do you just want my OPML file, or something more?

**Comment by yang991178** [comment]
> Can you explain what you want exported? Do you just want my OPML file, or something more?

You can export full app data under `Settings > Perferences > App Data > Export`. This includes everything stored by the app.

**Comment by mudfly** [comment]
I realized what you were asking for after I poked around in preferences, so I deleted my previous comment. Here is my App Data. Thank you for looking into this.

https://www.dropbox.com/s/1wz2b8pl78sjiqy/Fluent_Reader_Backup.frdata?dl=0
