### ISSUE TITLE
Where are preferences stored?

### ISSUE THREAD

**Issue by hybras** [yang991178/fluent-reader#295]
I'm creating a [homebrew](https://brew.sh) [cask](https://docs.brew.sh/Cask-Cookbook) for this app. It would be helpful to know what directories are used so they can be wiped [on uninstall](https://docs.brew.sh/Cask-Cookbook#stanza-uninstall).

**Comment by yang991178** [comment]
I believe those in the PR are the correct directories for DMG installation. However, I strongly people to install the app from MAS as that version is sandboxed, signed, and universal.

**Comment by hybras** [comment]
Thanks for the advice
