### ISSUE TITLE
HTTP/SOCKS5 Proxy

### ISSUE THREAD

**Issue by IlluminateDarkheat** [yang991178/fluent-reader#3]
Some of the RSS subscription sources I add are blocked by GFW, so I need to use an in-app proxy.
However, I noticed that fluent-reader currently only uses PAC proxies, and [the proxy software I use](https://github.com/Fndroid/clash_for_windows_pkg) only HTTP proxy and SOCK5 proxy are provided. Are developers considering adding the option to add HTTP or SOCK5 proxies?
Alternatively, consider invoking a system proxy.
Thank you very much for your efforts!

**Comment by yang991178** [comment]
PAC scripts are JS files that automatically match hostnames to proxies. Both HTTP and SOCKS5 are valid proxy protocols supported by PAC. You can easily find pre-configured PAC files (GFW-list, for instance) from the internet and set the port number of Clash to match the one provided by the script (usually localhost:1080).

**Comment by yang991178** [comment]
There is indeed an unintended bug to ignore system proxy settings when PAC is turned off. Thank you for bringing this up.

**Comment by yang991178** [comment]
Fixed in #5.
