### ISSUE TITLE
Not able to add Source

### ISSUE THREAD

**Issue by mrgodhani** [yang991178/fluent-reader#30]
**Describe the bug**
When trying to subscribe to specific news it is giving an Network error.

**To Reproduce**
1. Click Add new source
2. Try URL like https://theverge.com or https://techrunch.com
3. What I get is network error. Refer screenshot

**Expected behavior**
I should be able to add source

**Screenshots**
<img width="1213" alt="Screen Shot 2020-07-03 at 10 46 16 PM" src="https://user-images.githubusercontent.com/1529009/86503787-67e86080-bd7f-11ea-8ee8-838750c1774a.png">

**Desktop (please complete the following information):**
 - OS: macOS catalina

**Comment by yang991178** [comment]
The address of a source should be the URL of an XML feed. For instance, the full text source of The Verge is https://www.theverge.com/rss/full.xml. The network error prompt for parse error is a known issue and will be addressed. Thank you for pointing this out.
