### ISSUE TITLE
Inverted order for "Mark below/above as read"

### ISSUE THREAD

**Issue by davidcm** [yang991178/fluent-reader#301]
When right-clicking an article in the list, there's the submenu for "Mark as read". Maybe it's a small, unimportant usability detail but my OCD says the option "Mark above as read" should be above and "Mark below as read" should be below.

**Comment by yang991178** [comment]
This is actually an intentional design since I found myself using mark below as read much more frequently. Sadly there's no plan to change this or add OCD options :(

**Comment by davidcm** [comment]
That's a fair point, but let me try once more ;)
If the feature request #246 gets approved and implemented, would you reconsider this one? If the user sorts articles from oldest to newest, then probably the most frequently used action will instead be "mark above as read" :)

**Comment by yang991178** [comment]
I see your point. I'll keep that in mind.
