### ISSUE TITLE
backup files without opening the program

### ISSUE THREAD

**Issue by Ecarus-19** [yang991178/fluent-reader#305]
my win 10 (21H1) has broken boot and I can only reinstall the os

I tried to back up the fluent files but I was not able to do it

is there any way to get my data back ??

**Comment by yang991178** [comment]
If you installed through GitHub, the data should be in `<User Folder>\AppData\Roaming`. If you installed through Microsoft Store, it's under `<User Folder>\AppData\Local\Packages\<25286HaoyuanLiu.FluentReader followed by some string>\LocalCache\Roaming\fluent-reader`.
