### ISSUE TITLE
需求：代理配置疑问

### ISSUE THREAD

**Issue by fanlushuai** [yang991178/fluent-reader#319]
代理配置，为何要直接是http协议的pac？

要配置socket还需要，有一个http服务？

这个是不是多经历了一层转化，多依赖了一个http服务？

当我本机没有合适的http服务提供的时候，怎么办？

**Comment by yang991178** [comment]
这是chromium本身提供的接口的限制。有一些代理客户端本身就会自带http服务器，如果没有也可以上传到github pages或者在本机开一个http服务器来实现

**Comment by vagrant-psyche** [comment]
windows下可以用这个简单的方法设置代理:

找到安装路径下的Fluent Reader.exe文件，创建桌面快捷方式
修改快捷方式中的目标选项接入代理，添加后缀 --proxy-server=socks5://127.0.0.1:7890
注意引号后面需要加一个空格
我用的是clash，http和socks的代理端口都是7890
![Snipaste_2023-10-22_10-56-24](https://github.com/yang991178/fluent-reader/assets/37809377/ea2dc99c-2837-4f78-8e72-58d085fc4eab)
