### ISSUE TITLE
请问有关正则表达式匹配的问题

### ISSUE THREAD

**Issue by pikawindy** [yang991178/fluent-reader#321]
因为一点都不懂这方面的东西，请问如果我想  **标题或正文匹配到相关字眼 就标记已读或隐藏文章** 其中的**关键字**是用什么表达式呢？
能否提供个通用的公式？例如我想排除的关键字是**美国**，这个怎么搞呢？

请不吝赐教，谢谢

**Comment by Gez0377** [comment]
如果像同时填写既包括A,又不包括B, 这个表达式该怎么写?

**Comment by yang991178** [comment]
请参照https://zh.wikipedia.org/wiki/正则表达式
