### ISSUE TITLE
No Thumbnail Preview

### ISSUE THREAD

**Issue by viewsourc3** [yang991178/fluent-reader#322]
**Is your feature request related to a problem? Please describe.**
I assume this doesn't classify as a bug. It seems like the Linux version of Fluent Reader doesn't display any thumbnail preview for a given RSS entry, although this feature is displayed on [Fluent Reader's website](https://hyliu.me/fluent-reader/). 

**Describe the solution you'd like**
I wish Linux users could have a thumbnail preview next to each news entry

**Comment by JvTStar** [comment]
My thumbnails do not work even on services for which they should (e.g. It's FOSS)
![Screenshot from 2022-05-24 21-14-48](https://user-images.githubusercontent.com/91642609/170022268-745cd525-df85-408f-857b-d0ccd96177ef.png)
.
