### ISSUE TITLE
Request: Ability to copy the url of an existing feed

### ISSUE THREAD

**Issue by GiovanH** [yang991178/fluent-reader#330]
**Is your feature request related to a problem? Please describe.**

I often need to add an RSS feed from a site I'm already subscribed to (e.g. youtube, bridge) that just requires tweaking a query argument. I should be able to copy an existing one and tweak it there in settings.

**Describe the solution you'd like**

The URL of feeds in the Sources settings tab should either be copyable, or right-clicking it should copy the value to the clipboard.

**Comment by yang991178** [comment]
You can copy the URL further down in the page using the same dropdown for editing name/icon when selecting a feed.

**Comment by GiovanH** [comment]
Where? 
![image](https://user-images.githubusercontent.com/6759280/142792728-e4016a10-6c9b-48c1-ba1e-496da24a122f.png)

**Comment by skelerang** [comment]
Hi! I found my way here because I too thought URL's can't be copied. Could you please reconsider this?
Make the URL field above selectable or maybe explode the dropdown? Thanks.
