### ISSUE TITLE
解析xml信息流时出错

### ISSUE THREAD

**Issue by XiaoHuTongZhi** [yang991178/fluent-reader#331]
感谢作者开发的这款RSS阅读器。添加先知社区RSS订阅源出错。
先知社区订阅链接：https://xz.aliyun.com/feed
![image](https://user-images.githubusercontent.com/52963105/142374808-6889cee6-dc50-41f6-9ffe-c0e19d6078ba.png)

**Comment by wulouniu** [comment]
同样的问题，这是订阅链接 https://weekly.75.team/rss
