### ISSUE TITLE
awesome work! it can load 400MB xml feed

### ISSUE THREAD

**Issue by jian1929** [yang991178/fluent-reader#338]
i create a 400mb xml feed for my local pictures
i try freshrss and ttrss and quiterss,but it don't work ,this progect work well,like this:
[CDATA[<img src="http://127.0.0.1:8000/a1/003.jpg"
[CDATA[<img src="http://127.0.0.1:8000/a1/006.jpg"
[CDATA[<img src="http://127.0.0.1:8000/a1/010.jpg"
[CDATA[<img src="http://127.0.0.1:8000/a1/013.jpg"
[CDATA[<img src="http://127.0.0.1:8000/a1/016.jpg"

awesome work!!! but how make it fullscreen when i open a feed? thank u for your job

**Comment by yang991178** [comment]
If I understood you correctly, the closest thing available is to use list view in full screen.
