### ISSUE TITLE
Feature request: Adblocker in Fluent-Reader

### ISSUE THREAD

**Issue by xerhaxs** [yang991178/fluent-reader#346]
**Is your feature request related to a problem? Please describe.**
Problem: Some websites are not available via RSS, so you load them via "load whole website". Unfortunately, you then see annoying ads on most pages.

**Describe the solution you'd like**
Solution: My solution suggestion would be quite simple: An integration of an adblocker in Fluent-Reader, if you load the whole website. For example uBlock Origin, since this is also open source and works well.

**Comment by yang991178** [comment]
#281
