### ISSUE TITLE
[Feature Request] Display web page articles in a clear view

### ISSUE THREAD

**Issue by LoHub** [yang991178/fluent-reader#349]
First of all, thank you for your beautifull RSS reader. It is one of my daily tool.

**Is your feature request related to a problem? Please describe.**

Most websites doesn't provide full article content in RSS feed and have dirty website with pop-ups, advertisements, aggressive e-mail subscription requests, etc. Currently in fluent-reader, you can only choose between RSS content and full website.

**Describe the solution you'd like**

I would like to know if it is possible to add button to fetch full article on Web but displaying it in a clear view, focused on article. I think that a library like [Readability](https://github.com/mozilla/readability) from Mozilla could be easy to add and provide a good results.

Thank you very much.

**Comment by yang991178** [comment]
The newer versions of the app already has this feature built in.
