### ISSUE TITLE
Ability to set default view for specific subscriptions as webpage in desktop app

### ISSUE THREAD

**Issue by milindpatel63** [yang991178/fluent-reader#350]
**Is your feature request related to a problem? Please describe.**

Some feeds don't have full articles in their RSS feeds. Instead they have a URL like "Continue reading" at the bottom pointing to full article. But if we open that feed in webpage view, we can view the whole page.
Examples: Verge RSS feed.

**Describe the solution you'd like**

I would love an option to set default view to webpage for these specific feeds.
This option is available in the android app, but not in desktop windows app.

**Describe alternatives you've considered**

**Additional context**

**Comment by silverwings15** [comment]
The desktop app has this option, unless i've misunderstood what you meant

![image](https://user-images.githubusercontent.com/10742312/148807591-b13447e2-ff16-4709-b104-ef06a7b7706b.png)
