### ISSUE TITLE
Rules not working

### ISSUE THREAD

**Issue by HossBigft** [yang991178/fluent-reader#353]
**Describe the bug**
Rules have no effect whatsoever.

**To Reproduce**
1. Make a rule that hides and marks as read matching entries.
2. Check feed.
3. Refresh feed.
4. Nothing changes

**Expected behavior**
I expected  rule to hide and mark as read matching entries. However test shows expected results.

**Screenshots**
![image](https://user-images.githubusercontent.com/22785314/149303062-5a18a4c6-3d36-4824-a5bd-580ab872482a.png)
![image](https://user-images.githubusercontent.com/22785314/149303260-38de3c12-d885-4792-8f52-85a22470fe8e.png)
![image](https://user-images.githubusercontent.com/22785314/149303429-1c9fb49f-951a-415c-98e0-6dd652efda2a.png)

**Platform (please complete the following information):**
 - OS:   Windows 10 Pro 20H2 19042.1415
 - Version v1.1.0

**Comment by yang991178** [comment]
Rules only apply to newly fetched articles.

**Comment by HossBigft** [comment]
> Rules only apply to newly fetched articles.

Thanks for clarification. I think this detail should be mentioned in program and wiki.
