### ISSUE TITLE
Consider switching from electron to tauri

### ISSUE THREAD

**Issue by niwla23** [yang991178/fluent-reader#354]
Tauri is a new framework for desktop apps. It is written in Rust with GTK webview. It can render HTML just like electron but has a much smaller footprint on RAM and binary size.

https://tauri.studio/

I used it for a project once and it worked very well.

**Comment by yang991178** [comment]
This app relies heavily on features of electron and chromium, so I don't think it can be migrated to another platform without rewriting most of the code at least for now.
