### ISSUE TITLE
Freshly marked read articles still show in unread view

### ISSUE THREAD

**Issue by aklys** [yang991178/fluent-reader#357]
**Describe the bug**
When marking articles as read they don't disappear from the unread view until executing a refresh.

**To Reproduce**
1. Open App
2. Click on refresh 
3. Select View and set to unread only
4. Select "mark all as read" and apply to all articles
5. Articles still are displayed even though they are no longer marked as unread

**Expected behavior**
When marking an article as read it should disappear from the view

**Platform (please complete the following information):**
 - OS: Debian 11
 - Version: 1.1.0

**Comment by yang991178** [comment]
This is the intended behavior and is common among most of the other readers that i've used.

**Comment by aklys** [comment]
Guess I'm used to Google Reader and InoReader they always cleared them when marking all as read. Will get used to it then I guess lol thanks for the info.
