### ISSUE TITLE
Link to Flathub on your website

### ISSUE THREAD

**Issue by forteller** [yang991178/fluent-reader#359]
Hi. Loving this tool, thank you!

But at first when I found your website I though you didn't have a Linux version, since you have two big buttons for d/l on Windows and Mac. Then I saw the link underneath to GitHub, so I checked. Thankfully you do have a Linux version, but that was not as easy to see, and also the AppImage is not as easy to use perhaps for non-technical users.

Then I figured I'd just check if Fluent is available on Flathub, in case. And it was! Hurray!

All I want now is just a button on your website alongside the Win and Mac buttons for downloading from Flathub. Thank you! :)

**Comment by yang991178** [comment]
Thanks for the suggestion. However, there's no plan to provide links to the flathub version at the moment as it is maintained by unaffiliated volunteers and I can't guarantee its availability / functionalities.
