### ISSUE TITLE
Instant View (Reader mode)

### ISSUE THREAD

**Issue by Tarik02** [yang991178/fluent-reader#36]
**Is your feature request related to a problem? Please describe.**
It is not always convenient to read articles from different sites. Or maybe you want to read anything from the same place.

**Describe the solution you'd like**
I think, it would be very convenient to use [Telegram's instant view](https://instantview.telegram.org/) in order to present posts.

**Describe alternatives you've considered**
I don't know about any alternatives to this. Telegram has a great database of sites and how to get text from them.

**Additional context**
Instant view documentation: https://instantview.telegram.org/
Also, for implementation details, we can look at some of open-source Telegram clients.

**Comment by atbest** [comment]
I think you should consider https://github.com/mozilla/readability to improve readability.

**Comment by yang991178** [comment]
I don't think using Telegram instant view would be a good idea as it relies on websites to provide the necessary information and support is limited. Instead, Mercury Parser is integrated in Version 0.7.1 to provide a "reader mode". Please try that functionality out instead and feel free to provide further feedback.
