### ISSUE TITLE
Not Loading pictures or images in Card View

### ISSUE THREAD

**Issue by Josh-OS** [yang991178/fluent-reader#369]
Good day,

I have installed the app image of Fluent Reader for Linux; however the images and pictures are not showing.  In Card view only text is visible but no images.

![Fluent-CardView](https://user-images.githubusercontent.com/46802210/156293759-562d6117-fe2a-4ad4-8f6e-5ec8da658e6a.png)

Side note:
Full Content and Web Page view is working fine but Web Page view also automatically open the web browser which is annoying because the page is already loaded in the web page view of Fluent Reader, which means the website is both in my Fluent Reader and Web Browser.

Thanks.

**Comment by fligger** [comment]
I have the same problem

**Comment by yang991178** [comment]
If the XML/ HTML content of the RSS feed doesn't contain images, then no thumbnail can be shown. Please check if your feed indeed has images.

**Comment by adarsh1001** [comment]
Hi @yang991178, there are two examples of feeds that do contain the thumbnail images but are currently not being parsed by Fluent. One is from a popular anime [feed from MyAnimeList](https://myanimelist.net/rss/news.xml) where the thumbnail is specified within the `<media:thumbnail>` tag under each `<item>`. Another example is from The [Guardian's RSS feed](https://www.theguardian.com/world/rss). Here, each item has a `media:content` tag with the URL of the image and the width of the image as params. They specify it twice with 2 different widths; Fluent currently doesn't parse these but if we go about parsing them, we should ideally parse the higher width one.

As an example, the support for parsing these was [recently added](https://gitlab.com/spacecowboy/Feeder/-/issues/597#note_1113236780) in Feeder.

**Comment by ThomasHineXYZ** [comment]
How come this issue is closed? I'm having this issue with `media:thumbnail` tags in posts for YouTube channel feeds

![image](https://github.com/yang991178/fluent-reader/assets/6890628/fac92d1e-651c-49c1-bbd2-bc9e957b27ff)

**Comment by michael1maass** [comment]
same Problem hiere on windows: a frame is shown, but contains no image but the placeholder. since the frame shows (it doesn't show frames on Feeds that do not contain images) 

Any log that would record an error while loading the pics? 

Michael
