### ISSUE TITLE
Tray Icon

### ISSUE THREAD

**Issue by trymeouteh** [yang991178/fluent-reader#388]
**Is your feature request related to a problem? Please describe.**
To have the client run in the tray

**Describe the solution you'd like**
To have the client run in the tray. When you close the client by pressing the X button in the top right corner, it closes the window but keeps the client running in the background. To shut down the client you need to right click on the tray icon and click Quit.

**Describe alternatives you've considered**
Have a setting to have the client run in the tray or not.

**Additional context**
This will allow one to have the client running in the background like a email or messaging client and with the sync interval set to whatever the user wants, the user can get notifications on when a new article has arrived.

**Comment by yang991178** [comment]
#100
