### ISSUE TITLE
Broken icons

### ISSUE THREAD

**Issue by erasebegin** [yang991178/fluent-reader#398]
Hi, thank you so much for this wonderful app. 

![image](https://user-images.githubusercontent.com/1922075/161383329-4e99b7cb-4348-46bd-817f-b3b52eb539bb.png)

Shows broken image icon if icon is missing. It would look a lot better if the icon was simply removed if an icon is not found. Or perhaps a generic icon could appear instead.

**Comment by yang991178** [comment]
You can set the url of the icon manually in settings.
