### ISSUE TITLE
支持添加订阅源后修改订阅地址

### ISSUE THREAD

**Issue by Akijou-Lee** [yang991178/fluent-reader#421]
**Is your feature request related to a problem? Please describe.**
添加订阅源之后无法修改订阅地址，也无法复制粘贴，有些时候需要手写订阅地址，只能删掉重新添加，非常不方便。

**Describe the solution you'd like**
添加订阅源之后，可以选择修改或者删除源。

**Describe alternatives you've considered**
Nope.

**Additional context**
Not yet.

**Comment by yang991178** [comment]
#193 #258
