### ISSUE TITLE
Feeds generate Duplicates entries?

### ISSUE THREAD

**Issue by korason7117** [yang991178/fluent-reader#423]
**To Reproduce**
add this feed:
https://api.mangaupdates.com/v1/series/27507453126/rss

then refresh it.
then hide / mark as read or both
refresh again.
and you have them once again
if refreshed multiple times you'll have a bunch of duplicates

**Expected behavior**
It shouldn't fetch hided or marked as read or already fetched entries

**Platform (please complete the following information):**
 - OS: Archlinux up to date 
 - Flatpak App Version 1.1.0

**Comment by yang991178** [comment]
#286
