### ISSUE TITLE
请问怎么配置FreshRSS API到fluent-reader里？

### ISSUE THREAD

**Issue by RedStone365** [yang991178/fluent-reader#426]
我部署了最新版本的FreshRSS，官方提到的API地址为：http://FreshRSS服务地址/api/fever.php
浏览器请求该地址是没有问题的（已经在设置中开启了API）
但是选择Fever API，配置了端点（API地址）、用户名、密码之后，提示“请检查服务配置”。
请问有人使用FreshRSS的吗？我的版本是1.19.2
求解答。

**Comment by Whichbfj28** [comment]
https://XXX.com/p/api/fever.php
