### ISSUE TITLE
Xml parsing error

### ISSUE THREAD

**Issue by 91thu8u53rn433** [yang991178/fluent-reader#429]
Hi Yang991178,

The feed from https://unlimitedhangout.com/feed/ gives a xml parsing error, but the feed is displayed correctly on https://codebeautify.org/rssviewer. Can you take a look?

Kind regards,

**Comment by yang991178** [comment]
I don't see any issues when adding the feed, can you still reproduce this in the latest version of the app?

**Comment by yang991178** [comment]
The source loads fine on my side. It could be a problem of your network, or the source behaving nondeterministically. 
<img width="1312" alt="Screen Shot 2022-08-30 at 18 51 54" src="https://user-images.githubusercontent.com/16064741/187575209-67254a83-b691-41f7-8371-bc801c0c20be.png">

**Comment by 91thu8u53rn433** [comment]
Thx for checking. It's related to using a vpn service. I can't load the feed from this site, when I use vpn. Do you have an idea why this is the case? So far, I don't have problems with other feeds.
