### ISSUE TITLE
導入RSS錯誤

### ISSUE THREAD

**Issue by jerryc127** [yang991178/fluent-reader#43]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10 2004]
 - Version [e.g. 0.6.1]

**Additional context**

Fluent Reader v0.6.2 Beta
導入inoreader的xml 出錯
第一次導入  76個無法導入
第二次導入  83個出錯

![Snipaste_2020-07-24_21-40-04](https://user-images.githubusercontent.com/16351105/88397311-54686c80-cdf6-11ea-91a2-4e22eac137e5.png)
![Snipaste_2020-07-24_21-39-02](https://user-images.githubusercontent.com/16351105/88397316-55999980-cdf6-11ea-9df9-33a1d0fd7f66.png)

**Comment by yang991178** [comment]
目前不支持将同一个订阅源添加到不同分组，这些错误应该是因为订阅源已经存在了所以无法导入

**Comment by jerryc127** [comment]
新版解決了這個問題
感謝修復
