### ISSUE TITLE
希望可以增加个小功能：点击通知直接在浏览器中打开网页

### ISSUE THREAD

**Issue by ArsenicX** [yang991178/fluent-reader#44]
希望能可以 “点击通知直接跳转浏览器打开网页” 
现在点击通知只能跳转到应用，然后我再点菜单，再点“在浏览器中打开”，有点繁琐

**Comment by ArsenicX** [comment]
还希望能实现一个功能，就是按住 command⌘ 点击文章的时候可以在后台打开网页，不要把焦点转移到浏览器
使用场景：

**Comment by yang991178** [comment]
> 还希望能实现一个功能，就是按住 command⌘ 点击文章的时候可以在后台打开网页，不要把焦点转移到浏览器

新发布的0.6.3版本已经实现了，商店版还在审核。Chrome因为浏览器本身问题不能在后台打开，Safari和Firefox应该都没问题。

**Comment by ArsenicX** [comment]
> > 还希望能实现一个功能，就是按住 command⌘ 点击文章的时候可以在后台打开网页，不要把焦点转移到浏览器
> 
> 新发布的0.6.3版本已经实现了，商店版还在审核。Chrome因为浏览器本身问题不能在后台打开，Safari和Firefox应该都没问题（[相关链接](https://github.com/electron/electron/issues/12492)）。

哇谢谢大佬，感谢！🤩
