### ISSUE TITLE
Can't move the window

### ISSUE THREAD

**Issue by kkew3** [yang991178/fluent-reader#441]
**Describe the bug**
Upon open, the window can't be moved around by dragging with mouse the title bar or anywhere else.

**To Reproduce**
1. Launch `Fluent Reader.app`
2. Drag the window with mouse
3. See error

**Expected behavior**
The window should be moved like all other Apps.

**Screenshots**
![cant-move-window](https://user-images.githubusercontent.com/13264071/180347554-c95ad09b-3dcf-4cd0-98da-9b4cd05a3ec4.gif)

**Platform (please complete the following information):**
 - OS: macOS
 - Version 12.5

**Additional context**

**Comment by yang991178** [comment]
You may want to close the search input box first. I'll add more draggable space in the future.
