### ISSUE TITLE
an option for "Load Webpage by Default"

### ISSUE THREAD

**Issue by VenomSupreme** [yang991178/fluent-reader#442]
I use Fluent reader and like it, it's really cool.  
I use RSS feeds for youtube, it is less distractive and keeps you focused. BUT, the youtube videos only show as image in the reader along with description

to watch video I've to switch to "Load Webpage", where I can watch those videos. 
and there are other blog/articles too which I are better in webpage

I would like to request a option in preferences for "Load webpage by default", which would really help alot. 

another reader which I like has this option, but that has more than one flaws, and I like this more. so would love it if it becomes "perfect"

Thanks!

**Comment by yang991178** [comment]
This can be achieved in the feeds setting. Right click on a source in the menu and click on manage, then go to the bottom of the page to change default open target.

**Comment by VenomSupreme** [comment]
> This can be achieved in the feeds setting. Right click on a source in the menu and click on manage, then go to the bottom of the page to change default open target.

Yes sir, what I'm requesting is a option to toggle all of them, or select some of them and change the option for all of them in one click.

Currently, we can only select 1 and choose Default Open Target, if we select more than 1, it only shows option of deletion. 

It would be alot of convenience if we could change default Open Target for multiple feeds at once. 
I imported 100+ youtube channels, and had to do all of them manually, it's alot of work.

Hope you figure something out, 
This is A PERFECT READER. 
Thanks alot for your work, it saved alot of my time and helped me cure my youtube addiction, saved me from algorithms!!
