### ISSUE TITLE
已读内容变灰色

### ISSUE THREAD

**Issue by Jiang10086** [yang991178/fluent-reader#449]
你好，Fluent Reader的feed条目总是一样的白色，未能体现已读和未读的区别，在有大量RSS的条件下不能立即分辨出哪些读过。
如下图，“v2ex-分享创造”这个RSS只有4条未读，但右侧（第二栏）很是有很多条。
![图片](https://user-images.githubusercontent.com/67213568/185777842-8ef64309-a93a-42cd-9279-c25d91600e71.png)

**Describe the solution you'd like**
建议像reeder一样，已读的项目标题颜色变淡变灰，或者直接提供一个隐藏已读文章的选项。

**Comment by yang991178** [comment]
右键列表中文章-视图中可以淡化已读文章，右上角设置旁视图菜单可以筛选仅未读文章
