### ISSUE TITLE
Rules not working.

### ISSUE THREAD

**Issue by Shituation** [yang991178/fluent-reader#451]
**Describe the bug**
Tried all kinds of search for words to filter using the rules. Tried regex, tried normal, nothing works.
Are the filters working for already downloaded articles? (I'm using the HIDE action)

**Expected behavior**
To match a word with the filter and hide the article.

Rule:
![image](https://user-images.githubusercontent.com/43975882/186213284-610bba68-28e9-49f8-9bc6-611bc6bf06d1.png)

Article still there:
![image](https://user-images.githubusercontent.com/43975882/186213398-8340e5c0-2288-4ec1-b54a-99acd193f862.png)

**Platform (please complete the following information):**
 - OS: [Windows 10 ]
 - Version [19044.1889]
 - App version: 1.1.2

**Comment by yang991178** [comment]
The rules are for articles fetched after they're set up, not for existing articles.

**Comment by Shituation** [comment]
...and we cannot setup global filters BEFORE adding a new source, ending up with a lot of spam news from the first fetch.
