### ISSUE TITLE
Is it possible to make Fluent Reader force-import opml without any error warning?

### ISSUE THREAD

**Issue by Deleted-Account** [yang991178/fluent-reader#47]
I've set up RSSHub on my router and have subscribed hundreds of feeds.
But RSSHub is not always working properly. 
If I import opml to Fluent Reader, most of the feeds from RSSHub would get error.
Then if I import opml again, Fluent Reader would get errors and duplicated groups.

So is it possible to make Fluent Reader force-import opml?

Anyway, thanks for your great work.
Fluent Reader is the best RSS reader I have ever used.

**Comment by yang991178** [comment]
In version 0.7.0, importing sources from an OPML file multiple times no longer results in duplicated groups, so I will mark this as resolved.
