### ISSUE TITLE
How to increase font size?

### ISSUE THREAD

**Issue by peter099** [yang991178/fluent-reader#473]
I am using Fluent Reader flatpak version on MX Linux. My laptop screen resolution is 1920x1080 and rss feed titles and body text appear small. Is there a way to increase the font size?  In compact view, specially, feed titles are very small.

**Comment by yang991178** [comment]
I would suggest setting the UI scaling from your OS, as that would apply to every single app running. Currently only the article font size can be modified from the in-article menu. Duplicate as #347
