### ISSUE TITLE
[FEATURE] self hosted web based fluent reader

### ISSUE THREAD

**Issue by hgkamath** [yang991178/fluent-reader#481]
**Is your feature request related to a problem? Please describe.**
In addition to local install of various OS, also create  
1. **self-hosted variant**, in which the frontend running in the browser talks to a backend running on nodejs/deno. 
2. **in-browser PWA variant**, in which the whole app, both frontend and backend, run inside the browser, Data is manged/saved to a specified **cloud storage** location, using some sort of cloud-storage-connector.  

Then provide full instructions as to how to do so for layman user (ie how to start node/deno server) etc

Perhaps using cloud-storage should be a separate feature request issue for all local-variants, as it is a beneficial feature, even for non-browser local-app.  This is already filed as #467 "_custom location for database directory_"

**Describe the solution you'd like**
One should be able to browser to https ://127.0.0.1:someport/ or https ://127.0.0.1/fluent and a fluentreader-frontend should allow interaction with a fluentreader-backend. 
The self-hosted variant also opens possibility to put in podman etc.
This should allow one to set fluent-reader up to run having its data files pointing to some storage folder/location.
Then this same self-hosted server can be accessed from many browsers from different network locations.  
As fluent-reader is written in typescript, most things should just already work. 

Then,, maybe, the only extra things to take care of would be
- to manage frontend filehandling, that is to open(upload from browser)/save(download in browser) 
- to do user-login, per user folder, access control, 
- to handle simultaneous-multi-location-frontend-client-access

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by yang991178** [comment]
Thanks for the detailed suggestion. Linking this to #237 and closing as duplicate.
