### ISSUE TITLE
什么？订阅的RSS竟然没有保存在当前目录吗？

### ISSUE THREAD

**Issue by watertang** [yang991178/fluent-reader#486]
重装了系统之后，我的fluent-reader因为一直在系统以外的目录，所以我以为没有波及，就迫不及待地打开，结果傻眼了？！巴BQ了！所有之前订阅的RSS一个都没有了？！为什么软件就不能在订阅了之后在当前目录保存一下呢？导出是一个功能，但没有人会傻到每次新添加就导出一次的吧？！为什么一个这么基础的功能作者竟然没想到？！哭笑不得、欲哭无泪！

**Comment by zhjue** [comment]
@watertang 因为你fluent安装的目录可能并不一定有写入权限或者其他权限问题. 一般设置都是存在C盘的用户文件夹下那个appdata里的好像
