### ISSUE TITLE
Cannot move existing source to new group

### ISSUE THREAD

**Issue by alexwent** [yang991178/fluent-reader#493]
When I add a NEW source, there is no problem adding it to a group. However if I try to change the group of an EXISTING source, this is not possible. Currently the only workaround is to delete the source and re-enter it (!) at which point clicking on Group allows you to move the source between groups. 

Ideally (as others have noted) it would be good to be able to drag and drop sources not only within groups but between groups. 

Thanks in advance

**Comment by yang991178** [comment]
You can remove the source from a group after double clicking to open the group in settings, then add it to another group. I can look into ways to improve the editing experience in the future.

**Comment by alexwent** [comment]
Thank you. I get it now. May I recommend that you change the wording 'Delete from Group' to 'Remove from Group'? This small change would make things much easier to understand. 'Delete' suggests that you are permanently trashing the source, which is not in fact the case.

**Comment by Dapuva76** [comment]
I had to google this because I couldn't figure it out. Just posting to let you know it's still not entirely clear what to do, with the existing options/UI.
