### ISSUE TITLE
Sorry Noob Question Services 

### ISSUE THREAD

**Issue by thorrrr** [yang991178/fluent-reader#502]
HI 
Love the app but can you explain what service to use please and what does it do?
I have bought the IOS app but it asks me to pick a service!
I have the desktop app on Fedora and would like to sync to my IOS device
I have 2 servers i can host a service Proxmox and Unraid 
What do you recommend  i do not want any subscription service a free open sourse if possible :)

**Comment by yang991178** [comment]
I suggest checking out FreshRSS[https://github.com/FreshRSS/FreshRSS]. You should be able to sync with the service using either Fever API or Google Reader API once installed on your server.

**Comment by thorrrr** [comment]
Are you saying not to use Fluent Reader ?

**Comment by yang991178** [comment]
The service (FreshRSS, etc.) will fetch the articles and keep track of read status from your server, and this app will sync with your service instead of querying the sources.

**Comment by thorrrr** [comment]
I must be missing something in my services i get no option to pick FreshRSS!
![image](https://user-images.githubusercontent.com/8170673/209967273-4a308d8e-0f16-40ff-a7d7-465a4c657cf1.png)

I have FreshRSS setup on my server i have imported the opml file into FreshRSS they all show.
But how do i connect Fluent Reader to the service if it is not in your drop down box?
Where do i find the settings i have tried adding the suggestions from your docs 

Google Reader API
Supported since version 0.9.0.

Tested with The Old Reader (endpoint: https://theoldreader.com) and BazQuz Reader (endpoint: https://bazqux.com). FreshRSS with a version lower than 1.18 may not work properly.

Then add my FreshRSS username and API Password even tried FreshRSS password i get error

**Comment by yang991178** [comment]
When you visit the API URL given in FreshRSS settings (https://demo.freshrss.org/api/, etc.), you should see the URL to use for Google Reader API or Fever API on the webpage.
