### ISSUE TITLE
Add option for import twitter accounts

### ISSUE THREAD

**Issue by yhojann-cl** [yang991178/fluent-reader#510]
It would be a good idea for the application to have the possibility of obtaining content from twitter profiles since there are many news entities that do not use rss but do use twitter.

**Comment by zhoushengdao** [comment]
Why not use an RSS service like [Inoreader](https://www.inoreader.com/search/twitter)?

**Comment by yang991178** [comment]
Don't think this would be possible going forward with Elon pulling the plug on Twitter APIs, unfortunately.
