### ISSUE TITLE
无法添加RSSHub生成的订阅链接

### ISSUE THREAD

**Issue by JoeytheTranslator** [yang991178/fluent-reader#520]
**Describe the bug**
将RSShub生成的订阅链接复制到”添加订阅源“，并点击”添加“按钮后报错。

**To Reproduce**
1. 点击软件左上角的选项
2. 将RSShub生成的订阅链接复制到”添加订阅源“
3. 点击”添加“按钮
4. 报错
![image](https://user-images.githubusercontent.com/77867567/215519143-dadd23ac-38f7-48ba-af4d-ae45cb8471a6.png)

**Expected behavior**
支持添加RSSHub的订阅链接。

**Platform (please complete the following information):**
 - OS: Windows 11
 - Version [22621.1194]

**Comment by yang991178** [comment]
请检查你的上网环境，这是无法连接到rss hub服务器的问题。
