### ISSUE TITLE
v.1.1.3 will not start: Invalid file descriptor to ICU data 

### ISSUE THREAD

**Issue by caganer** [yang991178/fluent-reader#521]
Although the project page says Windows versions older than 10 may run packages from the GitHub archive this has failed at least so far with version 1.1.3 on Windows 7 Home Premium x64 with 0Patch Pro:

https://github.com/yang991178/fluent-reader/releases/download/v1.1.3/Fluent.Reader.Unpacked.1.1.3.x64.zip

- application will not start, error in log is:
[0131/230214.962:ERROR:icu_util.cc(225)] Invalid file descriptor to ICU data received.

**Comment by yang991178** [comment]
Not sure what the cause of this problem is, but Electron has dropped support for Windows 8.1 and previous versions. Only Windows 10+ will be supported going forward.
