### ISSUE TITLE
subscribe url support IP address

### ISSUE THREAD

**Issue by YU-7** [yang991178/fluent-reader#548]
![image](https://user-images.githubusercontent.com/58320198/231624868-4f005682-79e8-4f3c-bc10-0d4109849ecc.png)
as the picture show i can't subscribe the RSS with the IP address.

**Comment by JimenezLi** [comment]
Just add "http://" before your IP address.

**Comment by YU-7** [comment]
thanks，but a common think is that ip address don't have the "http://"
