### ISSUE TITLE
Can't use fever on Windows

### ISSUE THREAD

**Issue by Weilet** [yang991178/fluent-reader#55]
**Describe the bug**
Can't use Fever API on Windows

**To Reproduce**
1. Go to Service
2. Enter endpoint and other information
3. Press verify button

**Expected behavior**
Auth successful

**Screenshots**
![image](https://user-images.githubusercontent.com/32561597/89335635-de53e780-d6ca-11ea-878e-d1726e0ea4db.png)

**Platform (please complete the following information):**
 - OS: Windows 10 1903
 - Version 0.7.0

**Additional context**
It seems that the problem occur when I try to enter an endpoint like "{host}:{port}/plugins/fever/".
I tried my best to debug it but I failed.It's time to sleep.

**Comment by yang991178** [comment]
I will try to provide more useful error information in the next build. In the mean time, you can:

1. Clone the repo can run `npm run install` and `npm run start`. Proceed and see if any error message shows up in the dev tools console. 
1. Or, you can create another account in your TTRSS deployment and email me the credentials.

**Comment by Weilet** [comment]
By using dev tools console, I find it violates the document's Content Security Policy when you using endpoint with port.I think change CSP can solve this problem(I wish I can fix it myself but actually I know nothing about JavaScript)
