### ISSUE TITLE
Question / Idea - Installation with Homebrew

### ISSUE THREAD

**Issue by MrChocolatine** [yang991178/fluent-reader#60]
**Is your feature request related to a problem? Please describe.**

Just a simple question as [no one asked it yet](https://github.com/yang991178/fluent-reader/search?q=brew&unscoped_q=brew), do you plan to make it available via [Homebrew](https://brew.sh)?

**Describe the solution you'd like**

The possibility to install `fluent-reader` with Homebrew:

```sh
brew cask install fluent-reader
```

**Additional context**

Unfortunately I cannot help to do that, I just don't know how to.

Thank you.

**Comment by yang991178** [comment]
Currently there is no plan to add support for Homebrew or Scoop. Sorry about that.

**Comment by tillepille** [comment]
@yang991178 Would you be fine if I would create a cask and submit it to brew?
