### ISSUE TITLE
Sidebar menu wont stay open

### ISSUE THREAD

**Issue by DesperatePea** [yang991178/fluent-reader#612]
**Describe the bug**
In any view, the sources list menu to the left is supposed to stay, and you can chose to hide or open it. but now it hides automatically, and you need to click the menu button to make it appear. When clicking on anything else, the menu dissapear. Before, the menu stuck.
![bilde](https://github.com/yang991178/fluent-reader/assets/73502428/68b1a476-f7f2-485c-829e-a9e4d76f234e)

**To Reproduce**
Open the app, then go to card view. The left side menu is gone, and you need to click the menu button. Clicking outside of it hides it again.

**Expected behavior**
The menu should stay open, like the picture below:
![bilde](https://github.com/yang991178/fluent-reader/assets/73502428/2f3af54e-785d-4ee2-abba-37d609aaa321)
How it looks now:
![bilde](https://github.com/yang991178/fluent-reader/assets/73502428/d154b7f9-b22d-4c9f-ba36-fb896be2e732)

**Platform (please complete the following information):**
 - OS: Mac OS Sonoma
 - Version 14.0

**Comment by nemonein** [comment]
Hello. I'm on Archlinux with KDE.
I installed using aur. I tried both `fluent-reader-bin` as well as `fluent-reader` version. The result is the same.
This issue has not been solved at all.

<img width="1437" height="1009" alt="Image" src="https://github.com/user-attachments/assets/f35475d7-24db-4a5d-befa-293d4c7565fd" />

Could you please take a look again?
