### ISSUE TITLE
is this repo still being worked on or is dead???

### ISSUE THREAD

**Issue by shadow-absorber** [yang991178/fluent-reader#657]
not seen any updates or recent merges in a while and wondering if this is dead....

**Comment by yang991178** [comment]
Been planning to rewrite this for a while now. Will update the app when necessary.

**Comment by Alkarex** [comment]
@yang991178 As an alternative to rewriting a new app, you could consider joining one of the existing active open source projects such as:
* https://github.com/readrops/Readrops/
* https://github.com/Ashinch/ReadYou/
* [more existing apps](https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps)

What I observe is that there are several competing projects, but none yet that has achieved a high maturity, with support for essential features of the GReader API such as favourites (stars) and user labels, while having an efficient synchronisation mechanism.

References:
* [synchronisation strategy tips](https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html#synchronisation-strategy)
* [Synchronisation recommendation by Alkarex](https://github.com/FreshRSS/FreshRSS/issues/2566#issuecomment-541317776)
* [The Right Way to Sync by BazQux](https://github.com/bazqux/bazqux-api#user-content-the-right-way-to-sync)
* user labels / tag:
    * https://github.com/readrops/Readrops/issues/54
    * https://github.com/Ashinch/ReadYou/discussions/542#discussioncomment-8198277

[Alkarex](https://github.com/Alkarex), from [FreshRSS](https://github.com/FreshRSS/FreshRSS/)

**Comment by steveepreston** [comment]
@yang991178 Good News! 🎉

**Comment by steveepreston** [comment]
@Alkarex `fluent-reader` is for Desktop, not Mobile.

**Comment by Alkarex** [comment]
> [@Alkarex](https://github.com/Alkarex) `fluent-reader` is for Desktop, not Mobile.

My bad, I mixed it with fluent-reader-lite... But then one of the desktop projects, such as https://github.com/martinrotter/rssguard but it is indeed quite different

**Comment by steveepreston** [comment]
@Alkarex +1
`fluent-reader` is still best on my opinion. others has painful ui/ux

**Comment by steveepreston** [comment]
Good news. It's live again
