### ISSUE TITLE
有两个bug，一个是「点击通知直接在浏览器中打开」，一个是「未读文章会自动消失」

### ISSUE THREAD

**Issue by ArsenicX** [yang991178/fluent-reader#66]
第一个「点击通知直接打开浏览器」：
之前我在[这里](https://github.com/yang991178/fluent-reader/issues/44#issue-665515694)提了这个功能请求，但是好像有些问题：
当点击通知时，如果此时 Safari 是在全屏状态下，那么就会先在 Safari 中打开该网页，然后又跳转到 Fluent Reader 下在应用内打开这个网页；如果 Safari 不是在全屏状态下，那就是没问题的

第二个「未读文章会自动消失」：
出现过了很多次，有的文章我明明没有点开，想留着之后再看；但是晚上或者第二天的时候我就发现这个文章被标记为「已读」了

**Comment by yang991178** [comment]
`"跳转到 Fluent Reader 下在应用内打开这个网页"`指跳转到应用然后在应用窗口中显示该文章，还是在 Safari 打开网页后只跳转到应用？

第二点我个人还没有遇到过。

**Comment by ArsenicX** [comment]
@yang991178 
第一点：
指的是：我点击了通知之后，在 Safari 中就打开了网页，然后屏幕又跳转到了 Fluent Reader ,同时在 Fluent Reader 中打开网页。
我一直在等他发个通知，然后我好录屏发一下，结果一直没有通知....😅

第二点：
这就很奇怪了....我以前经常出现这情况

**Comment by yang991178** [comment]
> 第一点：
> 指的是：在 Safari 打开网页后只跳转到应用

这应该是mac或者electron在点击通知以后默认的行为，如果最小化窗口以后还会跳转到应用我也没办法了。

**Comment by ArsenicX** [comment]
@yang991178 
试了下，把 Fluent Reader 最小化之后确实不会再跳转了。
但是很奇怪，如果 Fluent Reader 没有最小化，同时 Safari 也没有最大化的时候，点击通知时 Fluent Reader 会闪现一下，然后再跳回 Safari
也就是说其实是可以跳转回 Safari 的，那怎么 Safari 最大化的时候就跳转不回去了....🤔️？

总之，如果是机制就这样设计的话那可能就没办法了。麻烦了谢谢😥
