### ISSUE TITLE
很多RSS都无法抓取

### ISSUE THREAD

**Issue by Alphabet1226** [yang991178/fluent-reader#7]
**Describe the bug**
软件十分优雅漂亮，可惜有些小瑕疵。
一方面导入（OPML文件是从Inoreader导出的）等待时间过长，要等一分钟到两分钟不定。
另一方面导入经常出问题，第一次导入三十多个只成功8个，之后又尝试了几次就是全部无法导入。过了两天后再尝试又成功导入几个，但还是有很多导入失败。
另外订阅源管理加个多选是不是会更好些?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 微软商店最新版

**Comment by yang991178** [comment]
微软商店最新版本是0.3.1，请问更新到这个版本了吗？
如果到最新版还有问题，请截图一下错误弹窗。
