### ISSUE TITLE
Miniflux Unread Count <> Fluent Reader Count 

### ISSUE THREAD

**Issue by CtrlAltDelete983422** [yang991178/fluent-reader#71]
**Describe the bug**
Logged into Miniflux web browser and checked the unread count of Reddit category.  It shows 182.  Did a sync on Fluent Reader and it shows the Reddit unread count at 149.  I then checked the Podcasts category unread count on Miniflux and it shows 53.  Fluent Reader shows 10.  It's just these two categories.  All my other categories are accurate.

**Expected behavior**
Expectation is that Fluent Reader unread counts match that within Miniflux web app  

**Screenshots**
![Fluent_Reader_RlG4jWDqJw](https://user-images.githubusercontent.com/69652380/90200923-e3025500-ddc8-11ea-8b14-810e398930c7.png)
![firefox_KsDm7jLTWn](https://user-images.githubusercontent.com/69652380/90200937-ea296300-ddc8-11ea-88e6-5cc21b375cc4.png)
![firefox_9WBZunpNwm](https://user-images.githubusercontent.com/69652380/90200944-ee558080-ddc8-11ea-9731-00e6a1a3de16.png)

**Platform (please complete the following information):**
 - OS: Windows 10 2004
 - Version 0.7.2

**Additional context**
Thank you

**Comment by yang991178** [comment]
The unread counts shown in the app are for the local items. Since there is a cap for the number of items synced with the service, it is normal for the counts to differ.

**Comment by CtrlAltDelete983422** [comment]
I did not read any items locally so on initial sync - since it was the very first sync, it should match what Miniflux reports on the Web, right?  I was well under the 1000 limit as well.  Am I misunderstanding?

**Comment by yang991178** [comment]
The limit applies to the total amount of items synced, including both read and unread articles.

**Comment by CtrlAltDelete983422** [comment]
It looks like it pulls down read items as well so maybe that's why.  That would likely push me over the 1000 limit.  I see that now.  was just typing
