### ISSUE TITLE
希望在“视图”中增加“无图列表”的模式

### ISSUE THREAD

**Issue by upindesign** [yang991178/fluent-reader#74]
无图列表模式中，只展示像下图中红框中的样式

![视图样式](https://user-images.githubusercontent.com/10083565/90332327-7a94bd00-dfee-11ea-8bca-4ae2fe98bb94.png)
![无图列表模式](https://user-images.githubusercontent.com/10083565/90332332-81bbcb00-dfee-11ea-8d21-b3e76a1e6339.png)

**Comment by yang991178** [comment]
在新版本中在列表视图下可以右键列表中的文章来显示/隐藏封面
