### ISSUE TITLE
Only Sync Unread Articles

### ISSUE THREAD

**Issue by CtrlAltDelete983422** [yang991178/fluent-reader#77]
**Is your feature request related to a problem? Please describe.**
To help stay under the 1000 latest article sync limit, add a setting to only sync the Unread articles.  Unless I clear out the history in Miniflux, both read and unread articles are synced which after a few days can easily put me over 1000

**Describe the solution you'd like**
add a setting to only sync the Unread articles

**Additional context**
Thank you for your consideration

**Comment by NoNamePro0** [comment]
This is a really good issue.

**Comment by yang991178** [comment]
In version 0.8.0, an experimental option to sync all articles (up until the latest article fetched in the last sync) is added. Please test that feature instead.

**Comment by CtrlAltDelete983422** [comment]
I tried the experimental option and it worked great.  Was fast too.  All categories show the correct amount of articles.  I had over 2000 plus articles to sync.  Thanks for your hard work!
