### ISSUE TITLE
建议增加手动同步功能

### ISSUE THREAD

**Issue by upindesign** [yang991178/fluent-reader#78]
当前最高抓取频次只能到10分钟一次，对于阅读速度比较快的人来说，还是显得慢了些，没有自主控制同步频次的操作感。建议增加手动同步功能（手动同步全部订阅源或针对某一个/某一组订阅源进行同步），就像outlook有自动同步邮件，同时也可以手动收取一样。

**Comment by yang991178** [comment]
右上角有刷新按钮（或按F5）。

**Comment by upindesign** [comment]
> 右上角有刷新按钮（或按F5）。

感谢
