### ISSUE TITLE
Hide read article in list only when switching to an other article

### ISSUE THREAD

**Issue by AceDenghar** [yang991178/fluent-reader#81]
**Is your feature request related to a problem? Please describe.**
Article is  immediately disappearing from list when selected

**Describe the solution you'd like**
It could change color in the list (to show it changed to read), and stay in the list until switching ton an other article.

**Describe alternatives you've considered**
Maybe it could stay in the list, with an other color, until switching feed/feed category

Thank you very much, that's a great job !
(sorry for my english)

**Comment by mkody** [comment]
I'd really like to see something like this being implemented.  
I've had issues when I'm changing between articles with keyboard shortcuts. Sometimes I go too fast and want to get back to the one I missed, but it's gone.
