### ISSUE TITLE
Hide empty groups/feeds

### ISSUE THREAD

**Issue by AceDenghar** [yang991178/fluent-reader#82]
**Is your feature request related to a problem? Please describe.**
Would it be possible to permit to hide/show empty groups/feeds ?

**Describe the solution you'd like**
It could be set in preferences with an option like "hide empty Groups/Feeds"

Thank you very much !

**Comment by yang991178** [comment]
Empty groups (groups without sources) are already automatically hidden. Unfortunately, functionalities other this won't be supported.
