### ISSUE TITLE
可以新增几个功能吗？

### ISSUE THREAD

**Issue by qingsongya** [yang991178/fluent-reader#89]
1、订阅源菜单栏，可设置为始终展开

2、加载网页，可设置为始终加载网页

3、文章列表，未读文章与已读文章的标题，有着明显的字体粗细与颜色深浅的区别

**Comment by MrWillCom** [comment]
> 3、文章列表，未读文章与已读文章的标题，有着明显的字体粗细与颜色深浅的区别

Hello, @Song-Ge . I've thought about the third suggestion, do you mean this:

![light-colored read items](https://user-images.githubusercontent.com/47271684/91656809-4fca5e80-eaee-11ea-8a3c-04daedf69739.png)

**Comment by yang991178** [comment]
1. 如果窗口够宽，菜单是固定显示的。
2. 设置里可以对每个订阅源分别设定始终加载网页。
3. 下个版本中列表视图下可以通过 `右键单击文章>视图>暗化已读文章` 来开启。
