### ISSUE TITLE
希望可以优化一下这几项

### ISSUE THREAD

**Issue by qingsongya** [yang991178/fluent-reader#93]
1、分类可以批量选择，进行删除操作。
2、增强一下主界面的功能呢，分组与订阅源，在主界面可以直接拖拽排序，无需到设置界面中操作，更加的方便快捷。
3、订阅源只能修改名称，不能修改订阅地址是吧？想要修改订阅地址，只能删除这个，创建新的订阅源？希望加个修改订阅源地址的功能。
4、开机不能自启在后台更新订阅数据吗，一定要在前台打开着？

**Comment by yang991178** [comment]
1. 个人不觉得有必要
2. #91 
3. 修改地址就不少同一个订阅源了
4. 请自行添加到开启启动应用列表

**Comment by qingsongya** [comment]
> 1. 个人不觉得有必要
> 2. [＃91](https://github.com/yang991178/fluent-reader/issues/91)
> 3. 修改地址就多个同一个订阅源了
> 4. 请自行添加到开机启动应用列表

虽然说分组批量删除不是很有必要，但是，如果想要清空分组，还要一个个的删除，很是麻烦。
修改订阅源地址，因为可能有这样的问题，用的是rsshub，如果换个别的域名rsshub，还要重建订阅源，重新获取文章内容，支持修改订阅源地址，也是为了方便，难道这样不方便，还是麻烦了不成？
