### ISSUE TITLE
希望加一个刷新功能，能够不用切换视图就消掉已读文章

### ISSUE THREAD

**Issue by ArsenicX** [yang991178/fluent-reader#94]
大佬好，这次更新，我看到了关于这个[ issue #81 ](https://github.com/yang991178/fluent-reader/issues/81)的改动。
老实讲改动前我用的很好，改动后让我的操作麻烦了不少

我平时只使用“只看未读”的模式，下面说的情景也都是在“只看未读”模式下的：
这次的改动使得所有文章，未读的和已读的文章全都是显示状态，时间一长整个界面文章堆积太多；
有的文章靠后，但是偏长；有的文章靠前，但是很短。因为时间关系看了新的短的，没看旧的长的，就导致界面显示的所有文章都是未读已读混在一起的，界面乱，尤其是在紧凑视图下。

我知道切换一下视图就能够把已读了的文章清除掉，可是这就导致我要么频繁的切换视图消掉已读，要么只能翻好多页找还没看的

<br><br>
我想到的解决方法：
可以加一个刷新功能？目的是让我在 “只看未读” 的视图下，刷新一下界面就能够消掉已经被标为已读的文章，而不用 「移鼠标 - 点”视图“按钮 - 点全部文章 - 点”视图“按钮 - 点未读文章」。太麻烦了
如果可以的话希望很能设置成快捷键，比如 command+R，习惯用浏览器默认的刷新键位了
谢谢大佬，麻烦了！！🤩🥺

**Comment by yang991178** [comment]
考虑下个版本在手动刷新（按F5或导航栏/Touch Bar的刷新按钮）后移除已读文章
