### ISSUE TITLE
关于数据存储的问题

### ISSUE THREAD

**Issue by qingsongya** [yang991178/fluent-reader#95]
我下载了uwp版和免安装版，把uwp版卸载了，打开免安装版，发现还是之前的数据，这个数据存在哪里？不是在程序的目录内吗？
希望免安装便携版，真的可以做到便携式，数据存储在程序所在文件夹内，移动到其它电脑上也可以继续使用。

**Comment by yang991178** [comment]
免安装版问题见#12。exe和zip版保存目录都在AppData/Roaming/fluent-reader，但是exe版卸载时会清理而zip版需要自行清理。如果在安装UWP版之前用过其它版本的应用并且没有清理目录则会读取这个数据，如果没有装过则是储存在UWP沙箱内。UWP卸载只会清理沙箱数据。
