### ISSUE TITLE
功能请求三个

### ISSUE THREAD

**Issue by naixzh** [yang991178/fluent-reader#97]
1.希望添加页面版式自定义【一行两列/三列/四列/自定义例】

2.内置代理接口【无奈啊，好的新闻网站都被蔷，rss都不正常】

3.希望能添进Google翻译内置【不知行得通吗】

**Comment by yang991178** [comment]
1. 分列可能不易阅读，个人觉得没有必要。
2. 代理可以通过PAC配置。
3. 请右键Google搜索单词或者直接浏览器打开翻译。
