### ISSUE TITLE
Next feed after mark all as read

### ISSUE THREAD

**Issue by jppaled** [yang991178/fluent-reader#98]
It can be possible that when you mark "all as read" on a feed, you move on the next feed automaticly, like feedly does.
It would be very convenient instead of mark all as read with F6 (or clicking on the icon), then pickup the mouse and click on the next feed.

**Comment by yang991178** [comment]
Unfortunately, I don't think that I will work on this feature as it introduces additional uncertainty to users and complicates this feature.
